### ISSUE TITLE
beidou性能问题

### ISSUE THREAD

**Issue by DXD23-SJTU** [alibaba/beidou#105]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
loadtest -c 8 -n 100000 ${url}
CPU立刻会吃满，但是页面渲染速度依然很快是为什么？RPS也是正常的，但是无论并发多少都会100%CPU吃满

**Comment by justquanyin** [comment]
建议：
1.  开启nodejs profile ， 查看下内存使用和GC调用，看是否存在内存泄露
2. 同构渲染本身也是会占用CPU资源进行计算，查看下自己的页面的DOM节点是不是特别多
3. 无论并发多少CPU都100%占用，估计是代码问题，还得自己慢慢调试

**Comment by DXD23-SJTU** [comment]
<img width="618" alt="46a9a6545531a8d13726cc11d1601072" src="https://user-images.githubusercontent.com/26563778/45870735-28c16900-bdbe-11e8-917a-128dec892152.png">
测试主要看tps数据 发张图警示下自己
