### ISSUE TITLE
helper能在client中使用吗

### ISSUE THREAD

**Issue by alex-my** [alibaba/beidou#109]
下午在看[安全](https://github.com/alibaba/beidou/blob/master/packages/beidou-docs/zh/core/security.md)文档，发现`helper`有好多函数: `helper.sjs()`, `helper.escape()`

这些函数能在 `client` （基于 advance 模板创建的）中使用吗？我试了试，都没能在`client`中使用，无法在 `React` 中用它们。demo 里面也没找到这些。

望指点。

**Comment by justquanyin** [comment]
可以使用的。
使用方式是： props.ctx.helper.escape()

**Comment by alex-my** [comment]
谢谢，回头我看看，是不是自己写的高阶组件把这个弄丢了。

**Comment by alex-my** [comment]
```text
export default class About extends React.Component {
  render() {
    return (
      <div>
        <h2>{this.props.ctx.helper.escape("<script>alert('hi')</script>")}</h2>
      </div>
    );
  }
}
```
输出:
` &lt;script&gt;alert(&#39;hi&#39;)&lt;/script&gt;`

确实是我自己弄没了。
