### ISSUE TITLE
webpack配置扩展

### ISSUE THREAD

**Issue by liutao** [alibaba/beidou#111]
扩展修改webpack的配置好费劲啊，比如我想给less加一个plugin，比如我就想xxx.less用用module。

**Comment by justquanyin** [comment]
能否详细描述一下问题，或者举一个例子

**Comment by liutao** [comment]
就比如我想给webpack里面less-loader加一个less-plugin-functions的plugin。有什么简便的配置方式吗？我翻了一下beidou-webpack，可以在custom里面配置一个configPath，然后可以在之前webpack配置基础上修改，我现在的做法是从module.rules里面找到哪个是配置less的loader，然后找到less-loader的options。
就比如umi里面，扩展less的plugin，只需要配置一个
```
lessLoaderOptions: {
        plugins: [new LessPluginFunction()],
},
```
它内部去做了merge。
或者说有神么我漏了的其他的方式？

**Comment by justquanyin** [comment]
嗯，暂时只能找到对应的配置项进行修改，后续我们会考虑加上auto merge的功能。
