### ISSUE TITLE
关于嵌套路径引用css和js文件的一些问题

### ISSUE THREAD

**Issue by jinyang1994** [alibaba/beidou#112]
* **Node Version**: 10.7.0
* **Beidou Version**: 1.0.9
* **Plugin Name And Version**:
* **React/ReactDOM Versions**: 16.2.0
* **Platform**: macOS 10.14 
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
目前我在client中创建了一个`pages`文件夹
并在下面创建我需要渲染的页面，对应路径是`pages/chart/bar.jsx`。
在controller中
```javascript
const { Controller } = require('egg');

class Chart extends Controller {
  async bar() {
    const { ctx } = this;

    await ctx.render('pages/chart/bar');
  }
}

module.exports = Chart;
```
我目前这样引用的我的`css`和`js`文件`helper.asset('chart/bar.js')}`，是404。
也尝试过`helper.asset('bar.js')}`、`helper.asset('pages/chart/bar.js')}`
我的问题是，我需要怎么样才能引用到该页面的`css`和`js`文件。

**Comment by justquanyin** [comment]
helper.asset()是可以使用的。
默认的地址是项目下的 ${appDir}/build/ 目录下
自定义可以在config中配置 react:{assetPath:"/your dir / asset_name.css"}
示例如下： 
`
react: {
    assetHost: 'g.alicdn.com',  // 
    assetPath: '/uedmid/udemo/0.0.14/',
  },
`

**Comment by jinyang1994** [comment]
@justquanyin 谢谢你的回答，我想知道的是，当我存在嵌套的情况下，`build`目录下生成的目录结构是什么样的？

**Comment by justquanyin** [comment]
build目录下是根据你webpack的配置生成的，详情还是要根据你自己的webpack配置来确定。

**Comment by jinyang1994** [comment]
@justquanyin 谢谢，我刚刚把webpack配置加上了，我以为beidou会有一些默认的处理。

**Comment by justquanyin** [comment]
原则上来说，如果项目中使用的import引入资源文件，是不需要特殊使用helper.asset()来引用资源的

**Comment by jinyang1994** [comment]
但是基础的HTML `layout`不是会需要用到`helper.asset()`嘛，就是这个时候，我引用文件时有的疑惑

**Comment by justquanyin** [comment]
原生的html，而非react的话确实是需要的。

**Comment by jinyang1994** [comment]
谢谢
