### ISSUE TITLE
感谢阿里出的这套react服务端渲染框架，这里是一些关于文档的建议

### ISSUE THREAD

**Issue by DXD23-SJTU** [alibaba/beidou#12]
首先贴出next框架的教程主页:https://learnnextjs.com/ 
我觉得next框架的2w颗星，这套教程功不可没。
        
- 鄙人作为react同构的新手与爱好者，曾苦于寻找一个框架，来免去我自己配置webpack的痛苦，直到我找到了next框架，在花了几小时做完他们的教程之后，发现这套框架的思想和同构非常贴切。教程教会了我路由切换，css的node兼容的解决方案等等。最大的便利之处就是，在阅读详细文档之前，这套教程几乎都对文档中的主要的点都点到了，但是并没有深入进去。

        

- 它的意义在于：对于新手，或者不熟悉这套框架但是熟悉同构思想的react爱好者，它带来的是广度上对于next的认识，而非深度上，有了广度的认识之后，爱好者可以快速上手使用它搭建hello world,或者带有fetch,简单路由功能的服务端渲染网站。
        在应用的过程中，爱好者可以从他们的github主页去获取详细的知识点，来解决需求。
        所以我的重点在于：先写出简单的教程，让爱好者迅速上车，理解框架思路，再后备详细的文档让他们查阅。比如cookie,session啊各自功能性文档。
        *个人想法：英文作为全球通用语言，对于国际化来说必不可少，但是作为中国人的我们，如果做出了成绩，写文档的时候首选中文的话，应该会增加中国互联网企业在世界的影响力吧，毕竟国内国外汉语开发者也不少。哈哈。
       最后的最后：谢谢阿里

**Comment by weichunpeng** [comment]
感谢你的建议，文档建设会作为我们的重点之一来建设，在新的Milestone发布出来

**Comment by yangfan0095** [comment]
最近看了很多同构项目 ，beidou确实不错。中文翻译这个 我觉得可以发动社区的力量 找一群热爱技术的人来做翻译，我觉得应该不难。这样不仅可以保证人力，也可以提升beidou的活跃度。而且在社区里面，对于翻译的人来说 这种参与感很重要。

**Comment by DXD23-SJTU** [comment]
不错哦

**Comment by weichunpeng** [comment]
@yangfan0095 中文文档已发布，详见 https://github.com/alibaba/beidou/blob/master/README-ZH.md

**Comment by netputer** [comment]
希望可以提供一个像样的官网，目前用 GitHub 目录的形式，浏览起来不太方便，看完一篇还得后退再点
