### ISSUE TITLE
Completely TypeScript Support

### ISSUE THREAD

**Issue by njugray** [alibaba/beidou#122]
## TypeScript 支持
Beidou V1 版本通过自定义babel配置，能够支持client代码使用 TS 编写，但对于 app 下的部分，无法提供支持。

**下一个 major 版本中，计划添加完整的 TS 支持，包括app下部分，增加北斗框架和插件的类型定义文件。**

## 实现方案

**Babel + TypeScript**

### Why  Babel ?

[egg的ts方案](https://eggjs.org/zh-cn/tutorials/typescript.html) 基于 [ts-node](https://github.com/TypeStrong/ts-node)

 dev 模式下启动辅助进程实时生成 `d.ts` 文件，使用内建的 ts-node 执行 ts 代码。

prod 模式下，需要实现编译所有ts代码为js，再启动应用。

然而 Beidou 同时包含 node.js 和 client 两个执行环境，在 client 这一侧，babel 一直是我们首选的方案。

如果 node.js 和 client 分别使用 ts-node 和 babel，两套执行环境势必增加复杂度和理解成本，而且二者的执行结果存在一致性风险。

因此可能的方案应该在 `ts-node + ts-node` 和 `babel + babel` 中选择。

目前来看 `babel + babel` 优势明显，理由如下:

- client 侧使用 babel，便于灵活扩展
- ts-node 不推荐在生产环境使用，势必多引入一个编译环节

> 这篇文章 [TypeScript With Babel: A Beautiful Marriage](https://iamturns.com/typescript-babel/) 阐述了TypeScript + Babel 的一些优点，有兴趣可以看看。

### 具体实现

Beidou V1 中，服务端的执行环境通过 **插件** `beidou-isomorphic` 提供，通过引入 `babel-register` 提供babel 运行时。

Egg.js 的插件加载机制导致 **通过插件提供运行时** 存在天然缺陷：**插件加载前运行时未生效**，其中包含应用的 **配置加载**，这也是 app 目录下无法支持 ts 的原因。

因此服务端运行时的注入需要提前，预期会做如下改动:

- 运行时不再作为插件的一部分，从 `beidou-isomorphic` 中独立出来
- 注入阶段提前：在 Agent 和 Application 构造之前
- `.js` 文件不再默认编译，确保框架层运行效率
- 提供默认配置，自定义配置以文件形式暴露，类似于.babelrc，命名为 `.node.babelrc`
- 在ts项目中，启动时同时开启 [egg-ts-helper](https://github.com/whxaxes/egg-ts-helper) (和egg保持一致，用于监听文件变更，生成 d.ts 类型文件)

## 后续工作

- [ ] 补充`.d.ts`类型定义文件
- [x] cli 新增 TypeScript 初始化模板

## 前置条件

#96 #95 

有任何想法和建议欢迎在此 Issue 下回复，墙裂欢迎何种 PR ！

**Comment by njugray** [comment]
@ahungrynoob beidou 一直都是babel + babel 模式，这个不难的，egg ts 最大的便利是 `egg-ts-helper` 在dev下动态生成 `d.ts`，这部分功能可以直接用

**Comment by ahungrynoob** [comment]
时隔一个多月再来看这段，仿佛有点顿悟。。。
