### ISSUE TITLE
支持 renderToNodeStream

### ISSUE THREAD

**Issue by andong-lad** [alibaba/beidou#124]
React 16 现已支持 Stream：
https://reactjs.org/docs/react-dom-server.html#rendertonodestream

是否可以考虑拆分 layout 和 container。先渲染出 layout 前半部分，然后渲染 container，pipe 到 res 上。stream end 之后，渲染 layout 后半部分。缩短首字节时间。

ReactDOMServer.renderToNodeStream(element)

**Comment by njugray** [comment]
@andong-lad  supported in v1.1.0
