### ISSUE TITLE
将beidou-webpack移至devDependencies中

### ISSUE THREAD

**Issue by justquanyin** [alibaba/beidou#132]
### 问题描述
beidou-webpack 依赖webpack-dev-server，在npm audit检测中会出报安全审核的问题。

### 解决方案
将beidou-wepack插件移动到devDependencies依赖中，并 默认仅在local/unittest环境下打开，其他环境默认关闭。

### 预计发布版本
v2.0

欢迎其他建议&PR。

**Comment by ahungrynoob** [comment]
npm audit 结果:
```
review  webpack-dev-server      high    >=3.1.6 Missing Origin Validation       https://nodesecurity.io/advisories/725  beidou-core>beidou-webpack>webpack-dev-server
review  hoek    moderate        > 4.2.0 < 5.0.0 || >= 5.0.3     Prototype pollution     https://nodesecurity.io/advisories/566  beidou-core>beidou-webpack>less>request>hawk>boom>hoek
review  hoek    moderate        > 4.2.0 < 5.0.0 || >= 5.0.3     Prototype pollution     https://nodesecurity.io/advisories/566  beidou-core>beidou-webpack>less>request>hawk>cryptiles>boom>hoek
review  hoek    moderate        > 4.2.0 < 5.0.0 || >= 5.0.3     Prototype pollution     https://nodesecurity.io/advisories/566  beidou-core>beidou-webpack>less>request>hawk>hoek
review  hoek    moderate        > 4.2.0 < 5.0.0 || >= 5.0.3     Prototype pollution     https://nodesecurity.io/advisories/566  beidou-core>beidou-webpack>less>request>hawk>sntp>hoek
review  assign-deep     low     >=0.4.7 Prototype Pollution     https://nodesecurity.io/advisories/579  beidou-cli>group-object>upsert-value>put-value>assign-deep
```
------
### 关于webpack-dev-server audit问题的解释:
https://www.npmjs.com/advisories/725
<br/> 升级到3.1.6以后版本即可解决

**Comment by justquanyin** [comment]
将devDependencies确认可以解决audit的问题。
正在实现的v2.0版本中， webpack-dev-server 版本已升级至3.1.9以上用以支持webpack4.代码在develop branch上。
webpack-dev-server本身应用也应仅是在开发环境or本地环境下，故避免造成不必要的影响，可以将其移至devDependencies中。
欢迎任何讨论&建议

**Comment by ahungrynoob** [comment]
将devDependencies能解决该问题 是什么原理？ npm audit默认会对devDependencies检测呀？

**Comment by justquanyin** [comment]
问题的出处是某位同学在 npm install --production后，使用 npm audit fix ，提示 webpack-dev-server 安全风险。
npm audit fix默认情况下，会扫描 dependencies 与 devDependencies，所以无论如何依赖，都一定会报webpack-dev-server的安全问题；但如果将 webpack-dev-server放入到devDependencies中，运行  npm audit fix --only=prod ， 可忽略 devDependencies 中的依赖。
当然，最好的方案一定是先升级webpack-dev-server到稳定版本，其次优化的地方才会是将依赖放入devDependencies，本也是解决线上部署时不需按照一些不需要的依赖库。
