### ISSUE TITLE
请问有官方微信群吗？麻烦拉我一下896559147 谢谢

### ISSUE THREAD

**Issue by nayonglin** [alibaba/beidou#134]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

**Comment by justquanyin** [comment]
![qrcode](https://img.alicdn.com/tfs/TB1tweoAHvpK1RjSZFqXXcXUVXa-674-896.jpg)
