### ISSUE TITLE
公共组件样式丢失问题

### ISSUE THREAD

**Issue by ForeverPx** [alibaba/beidou#138]
我们写了一个公共组件Nav，Nav里面import了Nav独有的less文件。
当Nav组件被三个以上的组件调用时，Nav组件的样式会全部丢失。
查看了最终的webpack配置，没发现有什么特殊的配置。
请问有什么可能会导致这种情况》

**Comment by justquanyin** [comment]
应该是公共模块的css样式被抽离到了manifest.css中。

**Comment by ForeverPx** [comment]
@justquanyin 感谢，已解决
