### ISSUE TITLE
headEntries有参考的文档吗？

### ISSUE THREAD

**Issue by ahungrynoob** [alibaba/beidou#141]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
发现`beidou-webpack`里有这么一段代码：
```javascript
if (dev && (devServer.hot || devServer.hotOnly)) {
    const port = devServer.port || app.options.port;
    headEntries = [
      `${require.resolve('webpack-dev-server/client')}?http://0.0.0.0:${port}`,
      require.resolve('webpack/hot/only-dev-server'),
    ];
  }
```
但是始终找不到这么使用webpack-dev-server的文档出处

**Comment by justquanyin** [comment]
Automatic Refresh 模式下的  Inline mode

**Comment by ahungrynoob** [comment]
默认inline模式就开启的，感觉headEntries不用加的样子。
https://webpack.js.org/configuration/dev-server/#devserver-inline

源码里在启动的时候，会添加的。
https://github.com/webpack/webpack-dev-server/blob/5ea376b768a85246a09b8af0ec0ffc1f43d26252/bin/webpack-dev-server.js#L133

**Comment by njugray** [comment]
去掉之后验证下能否work，来个PR @ahungrynoob

**Comment by ahungrynoob** [comment]
自己亲自试了下，发现去掉后就没有HMR的websocket请求过来了。。但是server端还是会保留`/sockjs-node/info`接口，因此单元测试可以通过。
下面这issue也试了一下，不行。文档真的太坑了。。。
https://github.com/webpack/webpack-dev-server/issues/1296
