### ISSUE TITLE
beidou-webpack的entry字段可优化的点

### ISSUE THREAD

**Issue by ahungrynoob** [alibaba/beidou#142]
reference: https://github.com/alibaba/beidou/blob/21c1f66fc518d89c0de447933b17d28c5b58ea1e/packages/beidou-webpack/lib/loader/entry-loader.js#L100

目前的表现：client/pages/的二级目录下，只有index.tsx会自动作为入口，（并且会以目录作为entry-name），如果有别的页面，则无法作为入口。

期望的表现：如果能递归遍历读取客户端的入口目录，岂不美哉？

**Comment by ahungrynoob** [comment]
另外一个可以优化的点：
由于这个不足之处，我会在`webpack.config.js`中修改entry配置。
但是:
```javascript
chokidar
      .watch(agent.config.client, {
        ignored: /(^|[/\\])\../,
        persistent: true,
        ignoreInitial: true,
      })
      .on('add', watcher)
      .on('addDir', watcher)
      .on('unlinkDir', watcher)
      .on('unlink', watcher);
```
在`chokidar`监听这些文件变动时，会触发`watcher`函数。
以下是`watcher`函数：
```javascript
function watcher() {
      const updatedEntry = entryLoader(agent, webpackConfig.devServer, true);
      if (!equal(updatedEntry, webpackConfig.entry)) {
        webpackConfig.entry = updatedEntry;
        helper.restartServer(webpackConfig, port, logger, agent);
        logger.info('[webpack:watcher] entry updated');
      }
    }
```
`watcher`函数中的`entryLoader`不会顾及custom-webpack-config.js，依然按照自己的逻辑去寻找入口，导致需要`ctrl+c`+`npm run dev`重新启动webpack-dev-server才可以继续进行开发工作，十分不便

**Comment by njugray** [comment]
递归遍历没有必要，目录层级较深的时候，各种组建目录都会被扫进去

watcher 函数在 updatedEntry 变化的时候才会去尝试重启 webpack, 强制重启才能继续开发的问题，需要详细定位下

**Comment by justquanyin** [comment]
> reference:
> 
> [beidou/packages/beidou-webpack/lib/loader/entry-loader.js](https://github.com/alibaba/beidou/blob/21c1f66fc518d89c0de447933b17d28c5b58ea1e/packages/beidou-webpack/lib/loader/entry-loader.js#L100)
> 
> Line 100 in [21c1f66](/alibaba/beidou/commit/21c1f66fc518d89c0de447933b17d28c5b58ea1e)
> 
>  name: entryName, 
> 目前的表现：client/pages/的二级目录下，只有index.tsx会自动作为入口，（并且会以目录作为entry-name），如果有别的页面，则无法作为入口。
> 
> 期望的表现：如果能递归遍历读取客户端的入口目录，岂不美哉？

说一下我的理解:
 目录遍历支持深度参数，可以使用参数config.custom.depth 来配置，而且也可以指定入口文件的文件名，配置项是config.route.entry。 
另外，对于递归遍历，个人理解，一般项目开发过程中，都是会有一个统一的项目目录结果与入口文件，我们能给出的只能是尽量满足大部分用户通用的使用方案

**Comment by ahungrynoob** [comment]
嗯，举个我工作中经常遇到的场景
![image](https://user-images.githubusercontent.com/26563778/52573132-6d749c00-2e54-11e9-99ab-e45d0de5a42d.png)
pages目录下都是入口页面，有PC端和移动端。目前m的移动端目录下，因为是二级目录，因此扫不到`bindmailverify.tsx`的入口页面，只会扫到`index.tsx`。因此需要我在`webpack.config.js`中手动添加
```javascript
const entry = factory.get('entry');
  const { port } = defaultConfig.devServer;
  entry.m_bindmailverify = [
    `${require.resolve('webpack-dev-server/client')}?http://0.0.0.0:${port}`,
    require.resolve('webpack/hot/only-dev-server'),
    require.resolve('../client/pages/m/bindmailverify.tsx'),
  ];
```
但是由于`chokidar`只会在文件、目录添加删除时才会重新扫一遍入口页面，因此会漏掉`bindmailverify.tsx`，这时候需要手动`ctrl+c`

**Comment by njugray** [comment]
这个问题是这样考虑的，一个复杂单页里，单目录下会包含有多个目录和文件，如：
![image](https://user-images.githubusercontent.com/5938871/52607734-3a60f580-2eb2-11e9-82b6-3804ab3af72b.png)

如果目录下的文件均被添加为 entry 是不可行的，entry 不可嵌套引用，webpack会挂。

你提到的问题可以通过添加目录 `/client/pages/m/bindmailverify/index.tsx` 解决

这也是 `router.entry` 设计原因之一，指定入口文件名称。

单个目录下所有文件都是入口，只适用结构简单的多页应用

**Comment by ahungrynoob** [comment]
哦哦，因为我这边的项目是多页面的场景很多，因此我这边是把入口页面专门放到`/client/pages`下了，也不会遇到嵌套引用的问题，然后那些组件代码放到`/client/对应入口页面名称`下面了，可以规避嵌套引用，webpack也不会挂，这么做的原因是以前用过`next.js`，它就是类似我现在的做法。
SPA的话，采用现在的beidou入口策略，不会有任何问题。
