### ISSUE TITLE
升级版本到2.0.1后，所有scss报错，只有less可用

### ISSUE THREAD

**Issue by WxSwen** [alibaba/beidou#143]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
升级版本到2.0.1后，所有scss报错，只有less可用；
降级回1.x后，不存在以上情况

**Comment by ahungrynoob** [comment]
有错误日志吗？

**Comment by WxSwen** [comment]
![image](https://user-images.githubusercontent.com/20021502/52950813-3e61ab80-33bb-11e9-83ec-b42c95360be8.png)
这是我刚才本地新建的（2.0.1），只要使用默认的less就可以，将less文件修改成scss就报错了

**Comment by justquanyin** [comment]
有 sass-loader 依赖么？

**Comment by WxSwen** [comment]
> 有 sass-loader 依赖么？

sass-loader的依赖应该是在webpack配置的，我这是直接使用默认配置.
1.x的时候也是直接使用的默认配置是没问题的，难道我需要覆盖webpack配置还是需要本地的sass-loader更新？

**Comment by ahungrynoob** [comment]
"sass-loader": "^7.0.0" 看下是不是这个版本

**Comment by WxSwen** [comment]
> "sass-loader": "^7.0.0" 看下是不是这个版本？
> 如果不是的话，不会加载.scss

我查看了run时的webpack.local.json 发现只有less-loader，不存在sass-loader
beidou init 的时候选择模式选择了simple有什么关系吗

**Comment by ahungrynoob** [comment]
@WxSwen `npm install --save-dev sass-loader `就完事了，没有`sass-loader`，内置webpack不会去解析.scss文件的

**Comment by WxSwen** [comment]
> @WxSwen `npm install --save-dev sass-loader `就完事了，没有`sass-loader`，内置webpack不会去解析.scss文件的
> https://github.com/alibaba/beidou/blob/master/packages/beidou-webpack/config/webpack/utils.js#L114
