### ISSUE TITLE
如何在构建的时候区分环境

### ISSUE THREAD

**Issue by WxSwen** [alibaba/beidou#144]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior

有个需求：测试环境和正式环境的前端某个资源链接地址不同，
在此之前可以通过env区分然后DefinePlugin设置全局变量获取，
在这个项目下，因为app.config.env构建时获取到的都是local，导致无法区分测试和线上；
请问这种情况有其他的方法吗？

## Expected behavior
希望代码能在npm script的时候就确定所有环境变量，而不是hard code在代码里面，每次都进行修改

**Comment by justquanyin** [comment]
默认给的app.config.env只有local和prod两个值
如果需要其他的环境变量区分的话，可以在build的时候加在环境变量中来做区分。

**Comment by njugray** [comment]
webpack插件只区分本地上线，因为在非本地环境下，插件不是启用，config.env 永远为 `local`。所以只能通过 `dev` 参数区分开发态和构建态

可以通过

```
beidou build --dev
```

或者

```
beidou build --dev=false
```
显式控制 dev 参数为 true 或 false

**Comment by WxSwen** [comment]
> webpack插件只区分本地上线，因为在非本地环境下，插件不是启用，config.env 永远为 `local`。所以只能通过 `dev` 参数区分开发态和构建态
> 
> 可以通过
> 
> ```
> beidou build --dev
> ```
> 或者
> 
> ```
> beidou build --dev=false
> ```
> 显式控制 dev 参数为 true 或 false

ok， @justquanyin 的方法也可以，用dev来也行，不过dev只接受boolean值，不过都受用

**Comment by WxSwen** [comment]
本来还以为跟egg的参数一样 类似使用--env=prod就行，结果出现其他问题； 
@justquanyin 的方法也可以，用--dev来也行，不过--dev只接受boolean值；

**Comment by ahungrynoob** [comment]
有一个办法，应该是和@justquanyin 一样的思想,`npm run build`的时候 设置环境变量，然后通过`process.env`获取就行了

**Comment by WxSwen** [comment]
> webpack插件只区分本地上线，因为在非本地环境下，插件不是启用，config.env 永远为 `local`。所以只能通过 `dev` 参数区分开发态和构建态
> 
> 可以通过
> 
> ```
> beidou build --dev
> ```
> 或者
> 
> ```
> beidou build --dev=false
> ```
> 显式控制 dev 参数为 true 或 false

请问build时--dev设置会影响到什么吗？为什么设置false和true打包出来的不一样？

**Comment by ahungrynoob** [comment]
dev true的时候是开发模式下的webpack设置模式，资源文件会加载到内存中，同时开始hmr，false的话就会把静态资源打包出来，放到build目录下

**Comment by njugray** [comment]
控制如 热替换，代码压缩，构建过程内置环境变量等

具体可以看下  https://github.com/alibaba/beidou/blob/master/packages/beidou-webpack/lib/utils/index.js#L101

**Comment by WxSwen** [comment]
> dev true的时候是开发模式下的webpack设置模式，资源文件会加载到内存中，同时开始hmr，false的话就会把静态资源打包出来，放到build目录下

好的，我看下

**Comment by ahungrynoob** [comment]
@WxSwen 嗯 同时还会把这个dev变量传进custom.webpack.js中，可以自定义webpack配置

**Comment by w3cui** [comment]
如果在项目中添加环境变量，我这里Api 接口地址 测试环境和正式环境域名不一样。 想用环境变量来实现，不知道怎么去添加？

**Comment by justquanyin** [comment]
你是想根据不同环境变量，使用不同的资源地址么？
可以看下 这个配置是不是你需要的
https://github.com/alibaba/beidou/blob/bd4bd5674fa1958a454866fbcb31b7a7e1a66235/packages/beidou-view-react/config/config.default.js#L28-L30
