### ISSUE TITLE
egg-redis v2.3.0无法连接codis-proxy，v2.0.0正常

### ISSUE THREAD

**Issue by chinacoolboyzz** [alibaba/beidou#145]
* **Node Version**: 10
* **Beidou Version**: 1.2.1
* **Plugin Name And Version**: egg-redis@2.3.0
* **React/ReactDOM Versions**: 16.2.0
* **Platform**: docker FROM node:8-alpine
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
egg-redis@2.3.0 无法正常访问codis-proxy
安装egg-redis@2.0.0可以正常访问codis-proxy

## Expected behavior
期望兼容codis

**Comment by ahungrynoob** [comment]
这个属于egg-redis的问题，不属于beidou

**Comment by chinacoolboyzz** [comment]
找到问题了codis不支持time命令
supportTimeCommand = false
解决
