### ISSUE TITLE
Build output files overwritten by Terser Plugin if comments extract enabled

### ISSUE THREAD

**Issue by njugray** [alibaba/beidou#148]
https://github.com/alibaba/beidou/blob/21c1f66fc518d89c0de447933b17d28c5b58ea1e/packages/beidou-webpack/config/config.default.js#L15

If  comments extract enabled，comments will be extracted to separated files with suffix `. LICENSE `。

With the default configuration of Beidou, which will leads to `[name].js?[hash].LICENSE`, reference to the same file, may cause source files overwritten by LICENSE files.

**Comment by justquanyin** [comment]
这个问题遇到过，开始的考虑是保留LICENSE的文件输出，但用户可以选择上传的文件中过滤掉LICENSE，既然有争议，可以去掉这个配置

**Comment by ahungrynoob** [comment]
[name]-[hash].js可以吗

**Comment by njugray** [comment]
[name]-[hash].js 的形式，文件不好引用

**Comment by ahungrynoob** [comment]
@njugray 
```javascript
module.exports = {
  assetWithHash(asset) {
    // 读取配置中的manifest
    const manifest = this.app.config.manifest || {};
    // 映射文件名
    let filename = asset;
    if (manifest[asset]) {
      filename = manifest[asset];
      return filename;
    }
    return this.helper.asset(filename);
  },
};
```
感觉利用ManifestPlugin
```javascript
const ManifestPlugin = require('webpack-manifest-plugin');
factory.addPlugin(ManifestPlugin, { fileName: '../manifest.json' }, 'WebpackManifestPlugin');
```
顺便解决 #55

**Comment by ahungrynoob** [comment]
哦哦
