### ISSUE TITLE
执行npm run build 之后未生成 manifest.js文件

### ISSUE THREAD

**Issue by yangbo5207** [alibaba/beidou#150]
如题

-->

* **Node Version**: 10.15.1
* **Beidou Version**: 2.0.1
* **Plugin Name And Version**: 6.23.0
* **React/ReactDOM Versions**: 16.6.3
* **Platform**: mac
* **Mini Showcase Repository**: 
* **Other Info**:

**Comment by ahungrynoob** [comment]
贴下你的webpack-config

**Comment by njugray** [comment]
给一下复现步骤吧


check 下本地 `run/webpack.local.json` 文件中

`optimization.splitChunks` 配置

**Comment by njugray** [comment]
#151

**Comment by yangbo5207** [comment]
感谢，已经解决了
