### ISSUE TITLE
build 过程中 webpack.optimization 配置丢失问题

### ISSUE THREAD

**Issue by njugray** [alibaba/beidou#151]
https://github.com/alibaba/beidou/blob/21c1f66fc518d89c0de447933b17d28c5b58ea1e/packages/beidou-webpack/config/webpack/webpack.browser.js#L66-L73

此处 factory.set 会导致 optimization 默认配置被覆盖

**Comment by ahungrynoob** [comment]
之前也发现  config.default.js文件没进去

**Comment by justquanyin** [comment]
@ahungrynoob  针对这个bug的fix，我的想法是，提供 wepackFactory.set方法为两种方式，一个是 覆盖式重写，一个是 深度merge，
https://github.com/alibaba/beidou/blob/master/packages/beidou-webpack/lib/factory/webpack.js#L96
```js
// const extend = require('extend2'); 
set(key, config, force = false) {

    if(force || is.string(config)){
      this.__webpackConfig[key] = config;
    }

    if (is.object(config)) {
      this.__webpackConfig[key] = extend2(true, this.__webpackConfig[key], config);
    }
    if (is.array(config)) {
      this.__webpackConfig[key] = this.__webpackConfig[key].concat(config)
    }

    return this;
  }
```

**Comment by ahungrynoob** [comment]
@justquanyin 好想法，这样minimizer就不会被用户的配置省略了，我来吧 怎么样～

**Comment by justquanyin** [comment]
> @justquanyin 好想法，这样minimizer就不会被用户的配置省略了，我来吧 怎么样～

哈哈哈哈，就是给你PR的建议哟

**Comment by ahungrynoob** [comment]
可以可以，又可以打怪升级拉
