### ISSUE TITLE
devServer 自动将 post请求转成了get请求

### ISSUE THREAD

**Issue by yangbo5207** [alibaba/beidou#153]
我在webpack.config.js中的配置如下
```js
devServer: {
      // @ts-ignore
      ...defaultConfig.devServer,
      disableHostCheck: true,
      contentBase: path.join(__dirname, "build"),
      compress: true,
      proxy: {
        '/api': {
          target: 'http://devgate.feewee.cn',
          pathRewrite: { '^/api': '' },
          changeOrigin: true,
          secure: false,
          bypass: (req, res, proxyOptions) => {
            console.log(req.method, req.url);
            req.method = 'POST';
            return req.url
          }
        }
      }
    },
```
在bypass中打印，发现所有的post方法都已经被转成了get请求，目前不知道到底是哪里执行的这个操作

* **Node Version**: 10.15.1
* **Beidou Version**: 2.0.1
* **webpack**: 4.29.5
* **React/ReactDOM Versions**: 16.6.3
* **Platform**: mac
* **Mini Showcase Repository**:
* **Other Info**:

**Comment by ahungrynoob** [comment]
```javascript
bypass: (req, res, proxyOptions) => {
            console.log(req.method, req.url);
            req.method = 'POST';
            return req.url // return req试试呢。。
          }
```

**Comment by yangbo5207** [comment]
@ahungrynoob bypass里的代码是我调试的时候加进入的，在这里执行之前post已经被转化成了get，我又手动在这里转回来的

**Comment by njugray** [comment]
https://github.com/alibaba/beidou/blob/8778b49d628767587f1ada4d24643d8494ef5ca9/packages/beidou-webpack/app/middleware/webpack.js#L9-L35

有关的逻辑应该在这里，转发请求到webpack的时候没有携带请求类型

**Comment by ahungrynoob** [comment]
@njugray 我感觉proxy设置了之后，会挡在这一步之前。

**Comment by njugray** [comment]
请求都是先发到 beidou，然后看情况转发的

**Comment by ahungrynoob** [comment]
懂啦，我修一下 带上method?

**Comment by yangbo5207** [comment]
我我感觉应该是在到webpack-dev-server之前请求类型已经被改了，但是不知道哪里改的

**Comment by ahungrynoob** [comment]
@yangbo5207 转到webpack-dev-server之后默认全转成get了，导致你那边丢失了post，没考虑到proxy

**Comment by njugray** [comment]
@ahungrynoob 带上method也是不够的，post请求里还有 body，需要把整个请求流 pipe 过去

**Comment by ahungrynoob** [comment]
@njugray 嗯嗯 就是这意思 表述有误 哈哈

**Comment by njugray** [comment]
这个中间件在实现的时候，主要是为了拿到资源文件，没有考虑使用 proxy 的场景，如果有 proxy，node 上写个路由自己转发一下就可以满足。

算是一个设计缺陷，这周修掉

**Comment by yangbo5207** [comment]
坐等 ~
