### ISSUE TITLE
with-react-loadable 案例运行报错

### ISSUE THREAD

**Issue by 18613109040** [alibaba/beidou#155]
export const Dynamic = Loadable({
> 17 |   loader: () => import('./dynamic'),
     |                 ^
  18 |   loading: () => <div>loading</div>,
  19 | });
  20 | 

Add @babel/plugin-syntax-dynamic-import (https://git.io/vb4Sv) to the 'plugins' section of your Babel config to enable parsing.

**Comment by justquanyin** [comment]
Would you like give us more example for the webpack config ? Because I try `@babel/plugin-syntax-dynamic-import ` into my webpack in beidou v4.0 , it work .

**Comment by njugray** [comment]
可以复现，需要更新一下依赖和配置
