### ISSUE TITLE
`extract-text-webpack-plugin`构建报错

### ISSUE THREAD

**Issue by ahungrynoob** [alibaba/beidou#159]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
// webpack.config.ts
```typescript
  const factory = app.webpackFactory;
  const plugin = factory.getPlugin('ExtractTextPlugin');
  plugin.options = {
    filename: dev ? '[name].css' : '[name]_[contenthash:8].css',
    allChunks: true,
  };
```

webpack打包时报错：
Error: Path variable [contenthash:8] not implemented in this context: [name]_[contenthash:8].css
reference: https://github.com/webpack-contrib/extract-text-webpack-plugin/issues/763
## Expected behavior
构建成功，并且css文件根据contenthash命名。

**Comment by ahungrynoob** [comment]
一种临时方案是`[md5:contenthash:hex:20]`，另外是采用`mini-css-extract-plugin`;beidou是否需要升级或者替代相关插件0 0？

**Comment by justquanyin** [comment]
ExtractTextPlugin插件本身的错误，可以考虑 mini-css-extract-plugin 替换。
要不来个PR吧

**Comment by ahungrynoob** [comment]
ok~

**Comment by justquanyin** [comment]
#178
