### ISSUE TITLE
 with-dva demo 出错

### ISSUE THREAD

**Issue by 18613109040** [alibaba/beidou#162]
执行npm run build  警告 ：WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.

You should also be sure that the version you pass to the `corejs` option matches the version specified in your `package.json`'s `dependencies` section. If it doesn't, you need to run one of the following commands:

  npm install --save core-js@2    npm install --save core-js@3
  yarn add core-js@2              yarn add core-js@3

执行 npm run start 发现 GET http://localhost:6001/build/manifest.js net::ERR_ABORTED 404 (Not Found)

**Comment by njugray** [comment]
prod环境下添加 static 配置，目录为 build

`config.prod.js`

```js

'use strict';

const path = require('path');

module.exports = {
  keys: 'secret',
  static: {
    prefix: '/build',
    dir: path.join(__dirname, '../build'),
  },
};

```

**Comment by njugray** [comment]
https://github.com/alibaba/beidou/commit/bd4bd5674fa1958a454866fbcb31b7a7e1a66235
