### ISSUE TITLE
服务端部署问题？

### ISSUE THREAD

**Issue by w3cui** [alibaba/beidou#163]
目前我启动dev环境，不知道怎么启动build 线上部署？ 求科普

**Comment by justquanyin** [comment]
具体命令可以查看使用beidou-cli。
一般情况下， dev是开发环境, start为production环境。
dev环境下，前端资源使用webpack devServer，所以不需要前端资源build就会被webpack捕获返回资源
production环境下，需要先使用beidou build，将前端资源打包输出后，再引用。一般默认资源打包输出在项目目录下的build目录中

**Comment by w3cui** [comment]
**问题描述：**
项目里面引用了的：manifest.js  在我npm run build打包后在线上运行时候发现文件里面引用了manifest.js 报404  而且bulid文件夹里面也没有manifest.js 文件，我如何能把manifest.js在正式包里面不让html文件里面输出manifest.js？
**下面是代码：**
```
<body id="container" dangerouslySetInnerHTML={{ __html: html }}></body>
<script src={helper.asset(`manifest.js?v=${version}`)} />
<script src={helper.asset(`${asset}.js?v=${version}`)} />

```

**Comment by justquanyin** [comment]
有点没明白。
你是获取manifest.js资源404的问题还是 不想引入 manifest.js 的问题？

**Comment by w3cui** [comment]
嗯！ 我在看运行npm run dev的时候manifest.js里面有内容，但是使用npm run build打包线上环境 运行的时候 manifest.js就不要了， 直接运行的<script src={helper.asset(`${asset}.js?v=${version}`)} /> 这个js就可以了！

**Comment by justquanyin** [comment]
npm run dev时， manifest.js 的资源是被webpack devServer匹配到返回的，所以本地build没有
npm run start 线上执行时，需要先将资源 npm run build,不过需要你在config.prod.js中将static配置一下你的资源目录。配置参考 https://github.com/alibaba/beidou/blob/bd4bd5674fa1958a454866fbcb31b7a7e1a66235/examples/advanced/config/config.default.js#L5-L19

**Comment by w3cui** [comment]
"scripts": {
    "start": "beidou  start --daemon",
    "debug": "beidou debug",
    "stop": "beidou stop",
    "dev": "beidou dev NODE_ENV=development ",
    "build": "beidou build NODE_ENV=production ",
    "build:node": "beidou build --target=node --env=prod"
  },
线上用"start": "beidou  start --daemon", 部署怎么一个请求cup就满了 ，是什么问题？

**Comment by justquanyin** [comment]
看下进程中是什么占用了CPU？ 另外可以使用heapdump看下内存占用。推荐使用alinode进行问题定位

**Comment by icewind7030** [comment]
请问建议把build操作放在构建流程里还是部署流程中比较好呢，文档中关于部署时build的流程好像不是特别清楚

**Comment by justquanyin** [comment]
> 请问建议把build操作放在构建流程里还是部署流程中比较好呢，文档中关于部署时build的流程好像不是特别清楚

build的目的是将前端资源打包，推荐在本地构建，然后将资源发到CDN
