### ISSUE TITLE
beidou-webpack打包less报错：CSS Loader Invalid Options

### ISSUE THREAD

**Issue by kapeter** [alibaba/beidou#164]
问题处在css-loader版本上：https://github.com/webpack-contrib/css-loader/issues/863

解决方案：删除minimize选项

**Comment by justquanyin** [comment]
可以问下，你是主动配置的项目的css-loader版本为2.0.0么？

**Comment by ahungrynoob** [comment]
可以贴一下工程的pkg.json，beidou 内置 ^0.28.x版本的css-loader，应用不需要自己添加css-loader了。。

**Comment by kapeter** [comment]
嗯，我是配了^2.0.0版本的css-loader导致报错了

**Comment by kapeter** [comment]
在with-less的例子中，css-loader是手动引入的，我是看了demo，自己引入css-loader
