### ISSUE TITLE
beidou 项目build报错，提示内存泄漏

### ISSUE THREAD

**Issue by Oligocalse** [alibaba/beidou#167]
![image](https://user-images.githubusercontent.com/36029402/55696228-947fc200-59ee-11e9-830a-a67ccf880214.png)
![image](https://user-images.githubusercontent.com/36029402/55696239-9f3a5700-59ee-11e9-8cf7-90346297886c.png)
![image](https://user-images.githubusercontent.com/36029402/55696253-ae210980-59ee-11e9-8f9d-00c105cb1925.png)

是这样的，在接到这次新的需求后，就从目前的线上分支同步代码到dev分支开始开发，在开发完成准备打包部署的时候发现build报错，于是就把dev中新增的代码git stash掉，但是仍然build报错

**Comment by ahungrynoob** [comment]
这段日志看不出问题，需要能看到webpack打包到哪一步的日志信息，我把我遇到的坑说一下吧，我遇到过npm run build 内存溢出的问题，记得当时好像`import`的时候，文件名大小写疏忽了

**Comment by Oligocalse** [comment]
> 这段日志看不出问题，需要能看到webpack打包到哪一步的日志信息，我把我遇到的坑说一下吧，我遇到过npm run build 内存溢出的问题，记得当时好像`import`的时候，文件名大小写疏忽了

我现在不知道为啥会内存泄漏，而且用了`increase-memory-limit`插件 或者 手动调大node运行内存也没有生效

**Comment by ahungrynoob** [comment]
找到webpack进行到哪一步就能定位问题

**Comment by Oligocalse** [comment]
> 找到webpack进行到哪一步就能定位问题

抱歉，现在才回复你。请问怎么知道webpack进行到哪一步呢？ 看webpack的打包日志吗

**Comment by ahungrynoob** [comment]
> > 找到webpack进行到哪一步就能定位问题
> 
> 抱歉，现在才回复你。请问怎么知道webpack进行到哪一步呢？ 看webpack的打包日志吗

有可以的复现的repo吗

**Comment by njugray** [comment]
@Oligocalse 这种内存泄漏问题一般是页面或者组件嵌套太复杂引起的，beidou的打包本质上和webpack打包没有区别。没有具体定位到问题来源不好解决。

可以尝试从webpack查找问题，参考这个issue：https://github.com/webpack/webpack/issues/1914

**Comment by Oligocalse** [comment]
> 给一个最小复现的repo吧

https://github.com/Oligocalse/beidou
麻烦你了！

**Comment by Oligocalse** [comment]
> > > 找到webpack进行到哪一步就能定位问题
> > 
> > 
> > 抱歉，现在才回复你。请问怎么知道webpack进行到哪一步呢？ 看webpack的打包日志吗
> 
> 有可以的复现的repo吗

https://github.com/Oligocalse/beidou
麻烦你了！

**Comment by Oligocalse** [comment]
> @Oligocalse 这种内存泄漏问题一般是页面或者组件嵌套太复杂引起的，beidou的打包本质上和webpack打包没有区别。没有具体定位到问题来源不好解决。
> 
> 可以尝试从webpack查找问题，参考这个issue：[webpack/webpack#1914](https://github.com/webpack/webpack/issues/1914)

好的！多谢啦！

**Comment by Oligocalse** [comment]
> @Oligocalse 这种内存泄漏问题一般是页面或者组件嵌套太复杂引起的，beidou的打包本质上和webpack打包没有区别。没有具体定位到问题来源不好解决。
> 
> 可以尝试从webpack查找问题，参考这个issue：[webpack/webpack#1914](https://github.com/webpack/webpack/issues/1914)

再请问一下，如何在webpack打包的时候看到打包日志呢？现在还是没有办法定位到错误，而且使用这个命令`node --max_old_space_size=32768 node_modules/.bin/beidou build`打包也依然报错

**Comment by njugray** [comment]
@Oligocalse 
用你的项目验证了一下：
webpack3, entry 数 25, build过程会出现issue中的问题，尝试只使用其中部分 entry，问题不会复现。
这个算是webpack3自身的问题。

尝试升级到 beidou 2.0，内置webpack 4，可以成功build，问题不再复现

![image](https://user-images.githubusercontent.com/5938871/57510661-f1e29800-7339-11e9-85eb-d8c1e52b7e04.png)

**Comment by Oligocalse** [comment]
> @Oligocalse
> 用你的项目验证了一下：
> webpack3, entry 数 25, build过程会出现issue中的问题，尝试只使用其中部分 entry，问题不会复现。
> 这个算是webpack3自身的问题。
> 
> 尝试升级到 beidou 2.0，内置webpack 4，可以成功build，问题不再复现
> 
> ![image](https://user-images.githubusercontent.com/5938871/57510661-f1e29800-7339-11e9-85eb-d8c1e52b7e04.png)

多谢大佬解答！
