### ISSUE TITLE
现有egg项目怎样和beidou融合

### ISSUE THREAD

**Issue by ladyzdp** [alibaba/beidou#170]
beidou和egg-beidou什么关系？
目前已经有了egg.js框架，理想的方案是将beidou以一个独立插件的形式融合到现有的框架中实现同构方案，如果融合到现有框架需要依赖哪些核心插件,具体的实现思路是什么。

**Comment by justquanyin** [comment]
egg-beidou设计的想法是纯粹的egg插件模式来支持SSR，不再在框架中定义其他的方式使用；如果想支持css-module 或者图片的同构，可以配合 beidou-webpack & beidou-isomorphic 来支持同构的资源渲染

**Comment by ahungrynoob** [comment]
beidou是基于egg的上层framework, egg-beidou是ssr插件
