### ISSUE TITLE
请问如果优化打包后的文件大小？

### ISSUE THREAD

**Issue by w3cui** [alibaba/beidou#171]
使用beidou打包的项目每个单应用都有1.5-2.5M  实在有点大  就打包了一个单页也要1M多！
我使用了 ant ui组件
控制台输出如下：
`WARNING in asset size limit: The following asset(s) exceed the recommended size limit (244 KiB).
This can impact web performance.
Assets:
  crazylist.js?a38bc175544810259f32 (1.48 MiB)
  detailed.js?a38bc175544810259f32 (1.49 MiB)
  error.js?a38bc175544810259f32 (1.44 MiB)
  foldup.js?a38bc175544810259f32 (1.48 MiB)
  goods.js?a38bc175544810259f32 (1.5 MiB)
  halfPrice.js?a38bc175544810259f32 (1.6 MiB)
  home.js?a38bc175544810259f32 (1.63 MiB)
  nine.js?a38bc175544810259f32 (1.61 MiB)
  home.css (613 KiB)
  nine.css (613 KiB)

WARNING in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (244 KiB). This can impact web performance.
Entrypoints:
  home (2.23 MiB)
      home.js?a38bc175544810259f32
      home.css
  goods (1.63 MiB)
      goods.js?a38bc175544810259f32
      goods.css
  detailed (1.62 MiB)
      detailed.js?a38bc175544810259f32
      detailed.css
  nine (2.21 MiB)
      nine.js?a38bc175544810259f32
      nine.css
  halfPrice (1.75 MiB)
      halfPrice.js?a38bc175544810259f32
      halfPrice.css
  foldup (1.61 MiB)
      foldup.js?a38bc175544810259f32
      foldup.css
  crazylist (1.61 MiB)
      crazylist.js?a38bc175544810259f32
      crazylist.css
  error (1.44 MiB)
      error.js?a38bc175544810259f32
      error.css`

**Comment by ahungrynoob** [comment]
babel-plugin-import这个babel的按需加载插件配置了吗

**Comment by w3cui** [comment]
有没有配置实例，我参考一下？

**Comment by ahungrynoob** [comment]
@w3cui https://ant.design/docs/react/introduce-cn 这里是说明文档哈

**Comment by alex-my** [comment]
如果有使用了 Icon，有了离线模式，这个在 antd 3.9 版本以后就蛮大了。

讨论: https://github.com/ant-design/ant-design/issues/12011

目前的解决方案: https://github.com/HeskeyBaozi/reduce-antd-icons-bundle-demo

**Comment by w3cui** [comment]
我什么代码都不写 ，就引用了一个react 建立一个路由 都有1M多。
我页面代码如下：
`import React, { Component } from 'react';
import { DeCodeUrlTest } from '../../components';
import error403 from './images/403.png';

import './style.less';
export default class Index extends Component {
  state = {
    item: false
  }
  componentDidMount() {
    const urlCode = DeCodeUrlTest(window.location.href);

    this.setState({ item: urlCode.r.indexOf('error_') >= 0 ? parseInt(urlCode.r.split("_")[1]) : 404 })
  }
  render() {
    const { code } = this.props;
    const { item } = this.state;
    return (
      <>
        {
          code === 403 ? <div className="error">
            <h1 style={{ paddingTop: '50px' }}><img src={error403} alt="" /></h1>
            <p style={{ fontSize: "18px" }}>当前无法访问 请稍后再试</p>
            <div></div>
          </div> : <div className="error">
              <h1>{(item && item) || (code && code)}</h1>
              <p>这个页面不存在  请检查来源是否正确？</p>
              <div><a href="/">返回首页</a>或者<a href="javascript:;" onClick={() => { window.history.go(-1) }}>返回上页</a></div>
            </div>

        }
      </>
    );
  }
}
`
这样打包出来都有1.5M
`  error (1.52 MiB)
      error.js?902a87c7cd7a3d7bc7f2
      error.css
`
感觉是react 太打了，能否把他提取出来 不放到打包里面，提取到公用里面引用 我要怎样去处理？

**Comment by justquanyin** [comment]
webpack配置 externals 项

**Comment by w3cui** [comment]
有没有案例，我这配置了 externals 打包还是一样没有什么作用？
`'use strict';

const path = require('path');

module.exports = (app, defaultConfig /* , dev */) => ({
  ...defaultConfig,
  entry: {
    home: [path.join(__dirname, '../client/pages/home/index.jsx')],
    goods: [path.join(__dirname, '../client/pages/goods/index.jsx')],
    detailed: [path.join(__dirname, '../client/pages/detailed/index.jsx')],

    nine: [path.join(__dirname, '../client/pages/nine/index.jsx')],
    halfPrice: [path.join(__dirname, '../client/pages/halfPrice/index.jsx')],
    foldup: [path.join(__dirname, '../client/pages/foldup/index.jsx')],
    crazylist: [path.join(__dirname, '../client/pages/crazylist/index.jsx')],

    error: [path.join(__dirname, '../client/pages/error/index.jsx')],
  },
  externals: {
    react: 'React',
    // 'react-dom': 'ReactDOM',
    // antd: 'antd',
  },
  resolve: {
    extensions: ['.json', '.js', '.jsx'],
    alias: {
      client: path.join(__dirname, '../client'),
      themes: path.join(__dirname, '../client/styles'),
    },
  },
});
`

**Comment by justquanyin** [comment]
你用的beidou哪个版本？

**Comment by w3cui** [comment]
"beidou": "^2.0.2",
    "beidou-cli": "^2.0.1",
我用的2.0.2

**Comment by justquanyin** [comment]
配置 webpack的optimization项，将共用类库单独抽离出来。
```
config.optimization.splitChunks = {
    chunks: 'all',
    name: 'manifest',
    cacheGroups: {
      default: false,
      vendors: false,
      manifest: {
        test: /[\\/]node_modules[\\/]/,
      },
    },
  }
```
