### ISSUE TITLE
引入antd-mobile 问题

### ISSUE THREAD

**Issue by 18613109040** [alibaba/beidou#172]
在with-dva demo 中
问题一：.babelrc 加入{ 
  "plugins": [
    [
      "import", {"libraryName": "antd-mobile", "style": true}
    ]
]
}不起效果，发现没有引入css 样式， 提示 You are using a whole package of antd-mobile, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size. 
问题2 我想引入 postcss-pxtorem  是否支持 postcss.config.js

**Comment by ahungrynoob** [comment]
第一个问题： 有demo的项目地址吗，可以检查下 入口页面有没有把打包的css资源加载进去。
提示 You are using a whole package of antd-mobile, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.这是服务端渲染的正常现象。
第二个问题： 支持的,通过webpack接入，在配置文件中指定自定义webpack配置即可。

**Comment by 18613109040** [comment]
测试demo地址：https://github.com/18613109040/beidou-antd-demo.git

**Comment by ahungrynoob** [comment]
我这边ok的 首页出来default字样

**Comment by 18613109040** [comment]
default  button 样式出不来

**Comment by ahungrynoob** [comment]
我这边看了下 css资源 js资源在dev和 start模式下都有了，如果没有出来default字样，要检查下代码的业务逻辑了。。
