### ISSUE TITLE
Need CLI tool to improve develop experience

### ISSUE THREAD

**Issue by devrsi0n** [alibaba/beidou#18]
Every example has a `bin/server.js` file wrote by hand to start the server, we can do start server logic in CLI tool.  Need a CLI tool just like [egg-bin](https://github.com/eggjs/egg-bin).

**Comment by njugray** [comment]
This feature can be integrated in `beidou-init`

**Comment by devrsi0n** [comment]
Commit package [beidou-bin](https://github.com/alibaba/beidou/commit/0cca74a8390e2432a7cfa0aa2c15093306a71b87)
