### ISSUE TITLE
init error , timeout.

### ISSUE THREAD

**Issue by ycjcl868** [alibaba/beidou#19]
I just run the commands according to the steps:   

```bash
$ npm install beidou-init -g
$ mkdir beidou && cd beidou
$ beidou init
```

request timeout, Why use npm registry not decide by user ?

![image](https://user-images.githubusercontent.com/13595509/34647968-aa395a00-f3cb-11e7-8ba0-bb1f0951247e.png)

**Comment by weichunpeng** [comment]
Thanks for your feedback. It was blocked by peculiar condition of Chinese network. You can use VPN to resolve this problems temporarily or manually download the beidou-example-simple package via [cnpm](https://npm.taobao.org/), and we will come up with a solution ASAP.

**Comment by ycjcl868** [comment]
😂 so the `beidou` boilerplate couldn't  use `cnpm` ,

**Comment by weichunpeng** [comment]
Source code committed in https://github.com/alibaba/beidou/tree/master/examples/simple and here is the [cnpm package link](https://npm.taobao.org/package/beidou-example-simple).  Have you any suggestions?
