### ISSUE TITLE
v2.2.1版本修改factory.getPlugin返回值无效

### ISSUE THREAD

**Issue by SugarTeam** [alibaba/beidou#193]
```js
factory.getPlugin("MiniCssExtractPlugin").options.chunkFilename = "[id].[chunkhash].css";
console.log(factory.getPlugin("MiniCssExtractPlugin").options);
```

![image](https://user-images.githubusercontent.com/43979048/62853071-d2368380-bd1d-11e9-85e4-466ae6fc36f9.png)

chunkFilename这个值还是原来的值

**Comment by justquanyin** [comment]
按照你给的代码，试了一下，是可以修改成功的。
不知道你给的这段代码是不是最小可复现的代码？
