### ISSUE TITLE
Build framework on the top of Beidou

### ISSUE THREAD

**Issue by Gorden-Wang** [alibaba/beidou#197]
https://github.com/alibaba/beidou/blob/ed56e7089591f6b6b87323d8e0d2fa474c6f29f4/packages/beidou-core/lib/beidou.js#L21

Beidou is an awesome React Isomorphic framework for server-rendered React apps，I want to build my framework on the top of Beidou.

I found a plugin ```egg-beidou```，but i also need to install ```beidou-webpack```,```beidou-isomorphic``` to use full beidou features。

I tried to build my ```framework``` inherited from ```beidou-core```, but i found the code above can not figure out my framework path 。

Any ideas pls contact me.

**Comment by njugray** [comment]
`beidou-core` is not like `egg-core` which is designed for extending by other frameworks.

If you want to build a framework on top of it, rewrite Beidou's `startCluster` may solve your problem.

But, the path of `framework` figure out where to load files of a framework, e.g. config files, app extend.

I'm not sure is this really works for you.

Any problem, comment this issue.

**Comment by Gorden-Wang** [comment]
@njugray Thanks for your reply.I I forked ```beidou-core``` and rewrite ```startCluster```, solved my problem indeed.
