### ISSUE TITLE
你们微信群 还是可以分享一下吗？

### ISSUE THREAD

**Issue by wunayou** [alibaba/beidou#22]
如题   中文文档 今年可以出来了吗？

**Comment by wunayou** [comment]
那一个介绍中的 微信群过期了

**Comment by weichunpeng** [comment]
@wunayou 微信群已更新，详见 [commit](https://github.com/alibaba/beidou/commit/6b91a16370d4f06ac613862f96b0bd04a93ce236)

中文文档计划本周发布出来

**Comment by weichunpeng** [comment]
@wunayou 中文文档已发布，详见 https://github.com/alibaba/beidou/blob/master/README-ZH.md
