### ISSUE TITLE
从零开始搭建应用 失败了

### ISSUE THREAD

**Issue by wunayou** [alibaba/beidou#23]
然后通过 app/router.js 来配置路由映射，相关 API 可以参考 koa-router 模块。

// app/router.js
module.exports = app => {
  app.get('/', app.controller.home);
};
好，现在可以启动应用来体验下。

$ node bin/server.js
$ open http://localhost:6001
**然后运行 提示  react  与 react-dom没有安装
然后就开始安装
接下就是这个错误了**
![image](https://user-images.githubusercontent.com/25662123/34979025-1611cfbc-fadb-11e7-9cbc-2364b8e72fc3.png)

**Comment by weichunpeng** [comment]
贴一下复现代码
