### ISSUE TITLE
案例也该更新一下了，里面的react版本还是15.x,现在都16.2了。

### ISSUE THREAD

**Issue by dxhuii** [alibaba/beidou#24]
如题。

**Comment by devrsi0n** [comment]
框架本身支持 react16，后面会把示例项目更新到新版。

**Comment by dxhuii** [comment]
@devrsi0n 嗯，有时间的话，升级下。

**Comment by devrsi0n** [comment]
develop 分支除了 performance（用于测试 react 版本性能）其余 react／react-dom 版本已更新到16.2.0。

**Comment by dxhuii** [comment]
@devrsi0n 嗯。感谢升级。响应的好快。
