### ISSUE TITLE
dev 分支兼容版本问题

### ISSUE THREAD

**Issue by andylei18** [alibaba/beidou#26]
会有这个警告:

📦   building modules(node:84499) DeprecationWarning: Chunk.modules is deprecated. Use Chunk.getNumberOfModules/mapModules/forEachModule/containsModule instead.

**Comment by devrsi0n** [comment]
可以贴一下最少复现代码吗？develop 分支 examples 应该没有这个 warning。

**Comment by andylei18** [comment]
@devrsi0n 我是手动 更新的Egg2 和 path 指向的dev分支 出的问题

**Comment by devrsi0n** [comment]
已发布 1.0.0-alpha.2 版本，使用 `yarn upgrade beidou-core` 升级依赖看看。

**Comment by devrsi0n** [comment]
beidou 全面升级了依赖，已发布多个 alpha 和 beta 版本，还请使用官方的 lib，如果还有问题可以继续回复。
