### ISSUE TITLE
从零开始搭建应用 无法启动

### ISSUE THREAD

**Issue by webaifei** [alibaba/beidou#269]
* **Node Version**: v12.16.1
* **Beidou Version**:2.1.1
* **Plugin Name And Version**: 无
* **React/ReactDOM Versions**:17.0.1
* **Platform**:Mac OS
* **Mini Showcase Repository**: 无
* **Other Info**: 无

## Current behavior
按照文档[从零开始搭建应用](https://github.com/alibaba/beidou/blob/master/packages/beidou-docs/zh/quick-start/step-by-step.md#%E4%BB%8E%E9%9B%B6%E5%BC%80%E5%A7%8B%E6%90%AD%E5%BB%BA%E5%BA%94%E7%94%A8)进行操作的时候 ，`npm run dev` 报错如下
```
[beidou-cli] v2.1.1
Error: beidou is not found 
....
```

## Expected behavior
能够正常启动

**Comment by webaifei** [comment]
any help?

**Comment by njugray** [comment]
添加依赖 beidou，`npm i beidou -S`

部分文档有过期风险，优先考虑使用脚手架初始化项目以及查看 examples 中的示例

**Comment by webaifei** [comment]
thk
