### ISSUE TITLE
beidou 性能问题

### ISSUE THREAD

**Issue by andylei18** [alibaba/beidou#27]
通过 wrk 压测，发现QPS很低， 超时很多，发送请求数很少。
数据如下:

➜  beidou-1 wrk -t4 -c250 -d60s http://127.0.0.1:6001
Running 1m test @ http://127.0.0.1:6001
  4 threads and 250 connections
  Thread Stats   Avg      Stdev     Max   +/- Stdev
    Latency     1.25s   316.27ms   2.00s    74.73%
    Req/Sec    42.63     22.23   120.00     58.81%
  10001 requests in 1.00m, 3.70MB read
  Socket errors: connect 0, read 79, write 0, timeout 188
Requests/sec:    166.44
Transfer/sec:     62.98KB

错误信息如下:
![image](https://user-images.githubusercontent.com/8412644/35623137-4505ae88-06c5-11e8-8ebf-0bb564b6004c.png)

**Comment by andylei18** [comment]
我是mac顶配 本机测试

**Comment by weichunpeng** [comment]
以下三个方面因素影响非常大

-  模板中默认版本是react15, 依赖升级到react16，性能会有非常大的提升，大约会在10倍左右
- 本地开发模式，默认NODE_ENV=local, 以 production模式启动，大约会提升 2-3倍
- node版本，node 8相比node 6会有30%左右的提升

可以试试这三个方面， 关于第一点，我们在升级默认的react版本了

**Comment by andylei18** [comment]
@weichunpeng 
1.react 版本这个我理解；
2.NODE_ENV 这个我觉得 约定的太死了，光我知道很多公司线上NODE_ENV不是production，是不是这块的耦合性太高了；
3. worker 数我理解跟部署期的cou核数相关；
4.我就是v8.9.3
5.Egg 本身的egg-view这个包就有性能问题；这个我测试过

**Comment by weichunpeng** [comment]
以[beidou simple example](https://github.com/alibaba/beidou/tree/master/examples/simple)为例, 根据我上面说的三个点(采用react16, production模式启动，去掉`worker=1`, 我本机起了7个worker), RT从21ms降低到了2.5ms左右(客户端采集到的RT，服务端RT大约还要减去1ms), 并发量从QPS40多升到了800以上(未压到极限)

![image](https://user-images.githubusercontent.com/13563689/35628889-2adc5454-06d8-11e8-9342-090cbece3159.png)

至于你说的egg-view存在性能问题，这个我会再跟进的

**Comment by andylei18** [comment]
@weichunpeng 收到 多交流。技术无国界
