### ISSUE TITLE
主进程会偶尔收到SIGTERM信号导致程序exit

### ISSUE THREAD

**Issue by canvasT** [alibaba/beidou#270]
* **Node Version**:v10.15.3
* **Beidou Version**:v2.2.1
* **Plugin Name And Version**:-
* **React/ReactDOM Versions**:16.14.0
* **Platform**:GNU/Linux
* **Mini Showcase Repository**: -
* **Other Info**: 
* 使用pm2启动（公司规范，必须使用pm2），启动指令: npx beidou start --port=8080 --title=xxx --env=test

## Current behavior

服务跑着跑着，egg-cluster/lib/master中会收到 SIGTERM 信号，从而exit所有子进程，导致服务异常

## Expected behavior

想了解什么情况会向master进程发送SIGTERM信号？
- app worker异常？
- 系统其它进程发送的？

**Comment by njugray** [comment]
https://github.com/eggjs/egg/issues/3885

**Comment by njugray** [comment]
一般是系统或者容器发出了 kill指令，建议检查下系统或容器的配置
