### ISSUE TITLE
可以默认支持 css modules ?

### ISSUE THREAD

**Issue by MinJieLiu** [alibaba/beidou#3]
`css modules` 或 `css in js` 的方案在实际开发过程中是必备的。可否不需要自定义 `webpack` 的配置，默认支持呢？

比如 `next.js` 默认支持的，`dva` 也是默认支持的

**Comment by njugray** [comment]
`css-modules` 的问题是这样的, 在我们的最初的方案中, 默认是开启的,  但实践的过程中, 发现绝大多数的业务(内部真实场景)都没有这个需求, 所以默认不开启.

自定义 `webpack ` 的问题, 目前的方案比较暴力(需要自定义一份完整的配置),  使用上确实不便. 接下来的迭代中会优化这个问题, 保持灵活自定义配置能力的同时, 简化部分配置项修改的难度, 比如通过参数定义开始 `css-modules`. 

这部分内容欢迎参与讨论, 给我们提意见.

**Comment by hoperyy** [comment]
我们公司目前是通过 配置文件暴露 快捷 API 和 待 merge 的 webpack 配置项，解决通用脚手架使用灵活性的问题。仅供参考。

**Comment by MinJieLiu** [comment]
或者如同 `dva` 中脚手架 `roadhog` 一样，给一份简易的配置，以后在脚手架升级成本就没那么大了。

**Comment by njugray** [comment]
默认开启 css-modules 会给不需要这个特性的使用者带来额外成本去关闭.  目前1.0版本中, beidou-webpack 供一份默认配置以供覆盖, 基本可以满足使用需要, 这个Issue先关闭, 如果有什么其他想法和建议, 可以再开issue一起讨论
