### ISSUE TITLE
从零开始搭建项目失败

### ISSUE THREAD

**Issue by leeyu0329** [alibaba/beidou#31]
![image](https://user-images.githubusercontent.com/12027046/36516662-1309d1b0-17ba-11e8-9b63-4c0b882d5ca3.png)

**Comment by devrsi0n** [comment]
把你的 config 目录下的配置贴出来看看

**Comment by leeyu0329** [comment]
const path = require('path');

module.exports = (appInfo) => {
    const config = {};

    config.react = {
        beautify: false,
        cache: true,
        static: false,
        doctype: '<!DOCTYPE html>',
        assetHost: '',
        assetPath: ''
    };

    config.view={
        defaultViewEngine:'react',
        defaultExtension:'.jsx',
        root:`${path.join(appInfo)}`
    }
};

**Comment by leeyu0329** [comment]
const path = require('path');

module.exports = (appInfo) => {
    const config = {};

    config.react = {
        beautify: false,
        cache: true,
        static: false,
        doctype: '<!DOCTYPE html>',
        assetHost: '',
        assetPath: ''
    };

    config.view = {
        defaultViewEngine: 'react',
        defaultExtension: '.jsx',
        root: `${path.join(appInfo.baseDir, 'app/views')},${path.join(appInfo.baseDir, 'client')}`
    };

    return config;
};

**Comment by leeyu0329** [comment]
从教程的上面到下面来看，还没有涉及到配置项，可能是教程不全

**Comment by devrsi0n** [comment]
你的 `client` 目录下有 `index.jsx` 这个入口文件吗？删了就会报这个错。

**Comment by leeyu0329** [comment]
哦哦，我晓得了，真是因为没有入口文件，不过这个文件从零开始搭建项目的时候一开始就没有，谢谢啦

**Comment by devrsi0n** [comment]
麻烦下次提交 issue 说明详细一些，只有一个截图定位问题比较麻烦。

**Comment by leeyu0329** [comment]
好的
