### ISSUE TITLE
启动正式服务器后，无法访问静态文件

### ISSUE THREAD

**Issue by wuww5511** [alibaba/beidou#38]
通过通过`beidou init` 生成的Simple项目。在`beidou build`后，通过`beidou start`启动服务，打开浏览器查看页面，发现静态资源的请求都返回404。通过`beidou dev`启动服务器时没有这个问题。

* **Node Version**: 8.9.4
* **Beidou Version**: beidou-cli@1.0.0, beidou-core@1.0.1
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:   react@16.3.1 , react-dom@16.3.1
* **Platform**: macOS
* **Mini Showcase Repository**: 通过beidou-cli生成的Simple项目
* **Other Info**:

## Current behavior
在`beidou build`后，通过`beidou start`启动服务，打开浏览器查看页面，发现静态资源的请求都返回404。

## Expected behavior

在`beidou build`后，通过`beidou start`启动服务，打开浏览器查看页面，可以成功返回静态资源文件。

**Comment by njugray** [comment]
config.prod.js:

```
module.exports = {
  static: {
    dynamic: false,
    preload: true,
  },
};
```

https://github.com/alibaba/beidou/blob/master/packages/beidou-core/config/config.prod.js#L10
此处配置 `dynamic: false`, 需要配合 `preload: true` 使用, 否者会出现找不到文件

或者修改 `dynamic: true` 也可以解决

**Comment by DXD23-SJTU** [comment]
真实原因应该是用了beidou组件后原来的egg-static的静态资源目录被移动到了/build下面,如果放在app/public下面的话 就会报404
