### ISSUE TITLE
没有中文的  英文不好 。进坑好累。。

### ISSUE THREAD

**Issue by zhouyingkai1** [alibaba/beidou#4]
D2听了这场 来学习一下。

**Comment by weichunpeng** [comment]
有中文的，中文文档比英文更完善，我们进行脱敏一下，然后放出来

**Comment by zhouyingkai1** [comment]
谢谢猴哥大佬 。🙏

**Comment by weichunpeng** [comment]
@zhouyingkai1 中文文档已发布，详见 https://github.com/alibaba/beidou/blob/master/README-ZH.md
