### ISSUE TITLE
client 二级目录下的文件不会被 webpack 打包

### ISSUE THREAD

**Issue by andong-lad** [alibaba/beidou#47]
* **Node Version**: 8.9
* **Beidou Version**: 1.0.2
* **Plugin Name And Version**: beidou-webpack
* **React/ReactDOM Versions**:  16.2
* **Platform**: mac
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior

* client **二级目录下** 的文件可以被自动路由，但是没有被 webpack 打包，entry 应该遍历一下二级目录。
* 例如：
![](http://p1.music.126.net/B3C-rQtJE-kP_B72M5Tufw==/109951163254847314.png)

http://localhost:6001/mobile/home/index 和 http://localhost:6001/home/index 都可以访问，但是 http://localhost:6001/mobile/home/index 是没有 js 和 css 的，因为没有进入 webpack entry：
![](http://p1.music.126.net/DgsZE8_cruh8jO3FfiicJw==/109951163254855175.png)

## Expected behavior
二级目录也能被 webpack 写入 entry 自动打包。例如上面的 `/mobile/home/index`。  chunk name 规范可以例如 `mobile-home`

**Comment by andong-lad** [comment]
自行解决了

**Comment by DXD23-SJTU** [comment]
怎么解决的能否说下？

**Comment by ForeverPx** [comment]
@andong-lad  请问怎么解决的呢？

**Comment by ahungrynoob** [comment]
举个例子
```javascript
const entry = factory.get('entry');
  const { port } = defaultConfig.devServer;
  entry.m_bindmailverify = [
    `${require.resolve('webpack-dev-server/client')}?http://0.0.0.0:${port}`,
    require.resolve('webpack/hot/only-dev-server'),
    require.resolve('../client/pages/m/bindmailverify.tsx'),
  ];
```

**Comment by njugray** [comment]
@andong-lad 可以设置entry扫描深度
```js
// config.default.js

{
  webpack: {
    custom: {
      depth: 2,
    }
  }
}

```

**Comment by ahungrynoob** [comment]
@njugray 
额 我试了下 没有效果 ，是在v2.0才有的功能吗

**Comment by njugray** [comment]
@ahungrynoob 需要升级到V2
