### ISSUE TITLE
feature request： config : router.root 支持数组

### ISSUE THREAD

**Issue by andong-lad** [alibaba/beidou#48]
## Current behavior

目前 router.root 只支持单个路径，例如

```
router: {
      root: '/pages',
},
```

## Expected behavior

希望 router.root 支持数组，例如

```
router: {
      root: ['/pages', '/mobile']
},
```

这样两个目录都可以被 beidou-webapck 自动加入 entry 打包。 尤其页面比较多 业务复杂的情况，页面是一定要分目录维护的。

**Comment by njugray** [comment]
新增支持entry扫描深度 `depth`, 默认是 1，也就是之前的默认行为，设置为 2 或以上，可以达到类似数组的效果

在 2.0 版本中生效
