### ISSUE TITLE
网络代理

### ISSUE THREAD

**Issue by 18613109040** [alibaba/beidou#53]
请框架有没有 代理的插件 像http-proxy-middleware 可以配置 proxy

**Comment by njugray** [comment]
参考: https://github.com/popomore/koa-proxy

**Comment by 18613109040** [comment]
module.exports = {
  proxy :{
    match:"/api",
    enable: true,
    package: 'koa-proxy',
    host:"http://baidu.com"
  }
}我要怎样配置，这样好像不行？
