### ISSUE TITLE
运行beidou v1.0.4 dev和build后编译报错

### ISSUE THREAD

**Issue by bobo717** [alibaba/beidou#60]
环境：
npm install beidou-cli -g
beidou init后选择css-modules，

运行npm run dev和npm run build一直报如下错误：

ERROR in ./client/utils/service.js
94:11-19 "export 'nodePost' was not found in './fetch'
 @ ./client/utils/service.js
 @ ./client/myPerson/app.jsx
 @ ./client/myPerson/index.jsx
 @ multi (webpack)-dev-server/client?http://0.0.0.0:6002 (webpack)/hot/only-dev-server.js ./client/myPerson/index.jsx

fetch.js部分代码如下：
module.exports = {
  fetch: function(method, url, params) {
    return new Promise(function(resolve, reject) {
      fetch(url, {
        method: method,
        // credentials: 'include',
        headers: {
          'Accept': 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(params),
      })
      .then((response) => response.json())
      .then((responseData) => {
        if (responseData.code === 0) {
          //请求成功
          resolve(responseData);
        } else {
          //返回错误
          reject(responseData);
        }
      })
      .catch((error) => {
        //捕获错误
        reject(error);
      });
    });
  },

./client/utils/service.js用 import { fetch } from './fetch';引入后即报错，过去使用beidou v0.3.5运行不会报错，使用beidou v1.0.4后报错。

**Comment by njugray** [comment]
尝试复现步骤：
1. `beidou init` 初始化 `css-modules` 示例

2. 添加 `client/utils/service.js`：

```

import { fetch } from './fetch';

console.log('fetch', fetch);

```

3. 添加到 `client/utils/fetch.js`：

```
module.exports = {
  fetch(method, url, params) {
    return new Promise(((resolve, reject) => {
      fetch(url, {
        method,
        // credentials: 'include',
        headers: {
          Accept: 'application/json',
          'Content-Type': 'application/json',
        },
        body: JSON.stringify(params),
      })
        .then(response => response.json())
        .then((responseData) => {
          if (responseData.code === 0) {
            // 请求成功
            resolve(responseData);
          } else {
            // 返回错误
            reject(responseData);
          }
        })
        .catch((error) => {
          // 捕获错误
          reject(error);
        });
    }));
  },
};

```

4. 在 `client/example/index.jsx` 下引入 `service.js`：

```
import '../utils/service';
```

5. 运行 `npm run dev` 和 `npm run build`

![image](https://user-images.githubusercontent.com/5938871/39752920-84cd4942-52ef-11e8-9f9d-11f2482c381e.png)

**运行正常，无法复现**

请提供可复现的步骤方便排查问题

**Comment by bobo717** [comment]
**复现代码目录：**
client
    ├── home
    |   └── index.jsx
    |   └── main.jsx
    └── utils
        └── fetch.js
        └── service.js

**index.jsx代码如下：**
import React from 'react';
import ReactDOM from 'react-dom';
import App from './main';

export default class View extends React.Component {
  static getPartial(props) {
    return {
			html: <App />,
    };
  }

  render() {
		const { helper, html } = this.props;
    return (
      <html>
        <head>
          <meta charset="UTF-8" />
          <title></title>
        </head>
        <body>
          <div id="container" dangerouslySetInnerHTML={{ __html: html }} />
          <script src={helper.asset('/manifest.js')} />
          <script src={helper.asset('/home.js')} />
        </body>
      </html>
    );
  }
}

if (__CLIENT__) {
  ReactDOM.hydrate(<App />, document.getElementById('container'));
}


**main.jsx代码如下：**
import React from 'react';
import service from '../utils/service';

export default class View extends React.Component {
  constructor(props) {
    super(props);
  }

  componentDidMount() {
    this.fetchData();
  }

  //请求数据
  fetchData = () => {
    service.no034()
    .then((ret) => {
      console.log('034', ret);
    })
    .catch((err) => {
      console.log('034', err);
    });
  }

  render() {
    return (
      <div></div>
    );
  }
}

**fetch代码如下：**
import 'whatwg-fetch';
import 'babel-polyfill';

module.exports = {
  post: function(url, params) {
    return new Promise(function(resolve, reject) {
      let body;
      if (params) {
        body = JSON.stringify(params);
      } else {
        body = JSON.stringify({});
      }
      fetch(url, {
        method: 'POST',
        // credentials: 'include', //设置传递cookies
        headers: {
          'Accept': 'application/json',
					'Content-Type': 'application/json',
        },
        body: body,
      })
      .then((response) => response.json())
      .then((responseData) => {
        if (responseData.code === 0) {
          //请求成功
          resolve(responseData);
        } else {
					//返回错误
					reject(responseData);
        }
      })
      .catch((error) => {
				//捕获错误
				reject(error);
      });
    });
  }
}

**service.js代码如下：**
import { post } from './fetch';

module.exports = {
  no034: function (params) {
    console.log('post', post);
  }
}

**运行npm run dev 和npm run build后均报错如下：**
ERROR in ./client/utils/service.js
1:103-107 "export 'post' was not found in './fetch'
 @ ./client/utils/service.js
 @ ./client/home/main.jsx
 @ ./client/home/index.jsx
 @ multi ./client/home/index.jsx

ERROR in ./client/home/main.jsx
1:1650-1657 "export 'default' (imported as 'service') was not found in '../utils/service'
 @ ./client/home/main.jsx
 @ ./client/home/index.jsx
 @ multi ./client/home/index.jsx

**Comment by bobo717** [comment]
谢谢
