### ISSUE TITLE
静态资源浏览器缓存问题

### ISSUE THREAD

**Issue by jxl893251217** [alibaba/beidou#61]
项目部署到线上，pc端刷新一下，页面就更新了，但移动端，刷新N多次有时候也没能更新出来。此时项目没做redis缓存或者其他cdn。请问这个问题怎么解决。是否压缩的时候文件名应该加上hash

**Comment by njugray** [comment]
推荐静态资源放到CDN中, 此时一般会带有版本控制, hash或者版本号

如果直接在应用上提供静态资源访问, 可以做类似的控制, 给资源加个版本号 如: `/public/index.js?v=1.0` 这种

**Comment by wunayou** [comment]
是不是移动端的缓存机制不一样啊？

**Comment by jxl893251217** [comment]
原来我pc端勾选了diable cache，去掉后，也是跟移动端一样的。然后也在资源后加过index.js?v=1.0了，但本地运行的时候，文件名后确实带上了版本号，可npm run build，再start的时候，版本后不见了

**Comment by njugray** [comment]
@jxl893251217 

1. 版本号应该是通过 `config.{env}.js` 配置(直接定义, 或者读 package.json 的version, 或者读取自定义生成的时间戳等等)

2. 在 `View` 中使用配置的版本, 如:
 ```
helper.assets(`index.js?v=${config.version}`)
```

不理解为何会出现 build之后再启动就失效的情况, 需要你描述下你的实现方式
