### ISSUE TITLE
同构后run start，页面重复渲染，一闪而过是修改后的内容，然后最后展示出来的是之前的内容。这需要如何去修改呢

### ISSUE THREAD

**Issue by jxl893251217** [alibaba/beidou#62]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

**Comment by njugray** [comment]
本地开发使用 `npm run dev`

**Comment by wind13** [comment]
使用 `npm run dev` 也是一样的，原因应该是没有自动 `build` 的问题。

不知道是要修改哪个配置，只要能每次修改源代码后运行 `npm run build` 应该就可以了。

**Comment by wind13** [comment]
找到一个可能的问题原因：
/config/ 目录下如果有 env 文件，请检查里面设置是 `local` 还是 `prod`，这个可能会决定服务器选择哪种启动模式，如果是 `local` 这个问题就好了。

**Comment by jxl893251217** [comment]
好的，谢谢
