### ISSUE TITLE
windows环境下yarn build报错

### ISSUE THREAD

**Issue by animecc44** [alibaba/beidou#63]
* **Node Version**: V8.9.3
* **Beidou Version**: 1.0.4
* **Plugin Name And Version**:
* **React/ReactDOM Versions**: 16.2
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior

yarn run v1.6.0
$ beidou build
[beidou-cli] v1.0.4
C:\Users\Administrator\web_project\node_modules\.bin\beidou-build:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at createScript (vm.js:80:10)
    at Object.runInThisContext (vm.js:139:10)
    at Module._compile (module.js:599:28)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
⚠️  Error: C:\Users\Administrator\web_project\node_modules\.bin\beidou-build --framework=beidou-core exit with code 1
⚠️  Command Error, enable `DEBUG=common-bin` for detail
error Command failed with exit code 1.

**Comment by chinacoolboyzz** [comment]
临时使用WIN10的LINUX子系统build

**Comment by animecc44** [comment]
安装了子系统在命令行bash转linux子系统后，build还是不行

**Comment by chinacoolboyzz** [comment]
rm -rf node_modules
先删掉node_modules在linux环境重新install

**Comment by animecc44** [comment]
万分感谢！

**Comment by njugray** [comment]
问题定位:
windows下 `node_modules/.bin/`目录下生成的 bin 文件为 `beidou-webpack.cmd` 和 `beidou-webpack` 分别对应 win cmd 和 linux shell 命令, 在 https://github.com/alibaba/beidou/blob/master/packages/beidou-cli/lib/commands/build.js#L50 中直接尝试运行了 linux shell 代码导致报错

临时方案:
修改 package.json 中 build script 为 `beidou-build --framework=beidou-core` 可以绕过此错误

下个patch 版本修复此问题
