### ISSUE TITLE
windows环境下ctrl+s使整个服务宕机，必须重新yarn dev才能继续

### ISSUE THREAD

**Issue by animecc44** [alibaba/beidou#64]
* **Node Version**:V8.9.3
* **Beidou Version**:1.0.4
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:16.2
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior

2018-05-22 11:23:37,805 ERROR 1244 nodejs.WebpackOptionsValidationError: Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should not be empty.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
 - configuration.entry should be one of these:
   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry should not be empty.
      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.
    * configuration.entry should be a string.
      -> An entry point without name. The string is resolved to a module which is loaded upon startup.
    * configuration.entry should be an array:
      [non-empty string]
    * configuration.entry should be an instance of function
      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.
    at webpack (D:\Web-project\jpkj-wechat-app\node_modules\webpack\lib\webpack.js:19:9)
    at startServer (D:\Web-project\jpkj-wechat-app\node_modules\beidou-webpack\lib\utils\index.js:172:20)
    at Object.restartServer (D:\Web-project\jpkj-wechat-app\node_modules\beidou-webpack\lib\utils\index.js:226:3)
    at FSWatcher.watcher (D:\Web-project\jpkj-wechat-app\node_modules\beidou-webpack\agent.js:31:16)
    at emitTwo (events.js:126:13)
    at FSWatcher.emit (events.js:214:7)
    at FSWatcher.<anonymous> (D:\Web-project\jpkj-wechat-app\node_modules\chokidar\index.js:199:15)
    at FSWatcher._emit (D:\Web-project\jpkj-wechat-app\node_modules\chokidar\index.js:241:5)
    at FSWatcher.NodeFsHandler._handleFile (D:\Web-project\jpkj-wechat-app\node_modules\chokidar\lib\nodefs-handler.js:276:10)
    at FSWatcher.<anonymous> (D:\Web-project\jpkj-wechat-app\node_modules\chokidar\lib\nodefs-handler.js:474:21)
name: 'WebpackOptionsValidationError'
message: 'Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.\n - configuration.entry should be one of these:\n   object { <key>: non-empty string | [non-empty string] } | non-empty string | [non-empty string] | function\n   -> The e
ntry point(s) of the compilation.\n   Details:\n    * configuration.entry should not be empty.\n      -> Multiple entry bundles are created. The key is the chunk name. The value can be a string or an array.\n    * configuration.entry should be a string.\n      -> An entry point without name. The string i
s resolved to a module which is loaded upon startup.\n    * configuration.entry should be an array:\n      [non-empty string]\n    * configuration.entry should be an instance of function\n      -> A Function returning an entry object, an entry string, an entry array or a promise to these things.'
validationErrors: [ { keyword: 'anyOf', dataPath: '.entry', schemaPath: '#/properties/entry/anyOf', params: {}, message: 'should match some schema in anyOf', schema: [ [Object] ], parentSchema: { description: 'The entry point(s) of the compilation.', anyOf: [Array] }, data: {}, children: [ [Object], [Obj
ect], [Object], [Object], [Object], [Object] ] } ]
pid: 1244
hostname: PC-201805181637

**Comment by njugray** [comment]
报错信息: `configuration.entry should be one of these: ...`

标识当前 webpack 配置中没有有效的 entry

在修改文件名, 删除文件时, beidou 会监听文件变化, 重新计算默认entry, 如果最终entry为空, 会导致上述错误

重新添加entry, 会自动恢复. 

或者在控制台输入 `rs` + `enter`, 强制重启webpack server

在 windows 10 + cmd/mingw 下测试生效

**Comment by njugray** [comment]
@animecc44 服务重启宕机的问题我没能复现, 麻烦提供下详细信息:
1. 系统版本
2. shell 类型和版本
3. 使用了哪个example工程
4. 在新初始化的工程下是否存在此问题

**Comment by animecc44** [comment]
@njugray 

1.系统版本号：windows 10 专业版 64位（10.0 版本16299）
2.shell类型和版本：Major  Minor  Build  Revision
                                -----  -----  -----  --------
                                5      1      16299  64
3.example为antd-admin
4.新初始化的工程下也存在此问题

**Comment by ahungrynoob** [comment]
我也发现类似问题，由于我自定义添加了一些entry，导致ctrl+s的时候，自定义添加的entry会失效，此时需要重新`npm run dev`，能不能在监听文件变化的时候，重新计算最近一次的entry，这样做的话会不会有什么问题，比如`添加了一个入口文件`这样的变化就收录不到了

**Comment by njugray** [comment]
@ahungrynoob 

https://github.com/alibaba/beidou/blob/master/packages/beidou-webpack/agent.js#L28

你说的这个逻辑已经有了的，mac下是好的，我在windows虚拟机里一直没有复现

**Comment by njugray** [comment]
No more feedback, close
