### ISSUE TITLE
客户端的 i18n 解决方法？

### ISSUE THREAD

**Issue by wind13** [alibaba/beidou#66]
看到文档中讲“多语言”，应该只是服务端的 `i18n` 解决方案。而北斗框架是结合 React.js 的，不知道在 React.js 这边怎么使用呢？比如说 *.jsx 文件中怎么实现 `i18n` 呢？ 还是说要自己添加相应的第三方库？

**Comment by njugray** [comment]
`react-intl` 了解下

**Comment by wind13** [comment]
多谢，应该考虑直接整合到北斗框架中，呵呵……
