### ISSUE TITLE
示例antd-admin的旧版IE兼容

### ISSUE THREAD

**Issue by jijunzeng** [alibaba/beidou#67]
2345，360之类的浏览器，跑antd-admin的示例，axios请求都失效……

**Comment by justquanyin** [comment]
已下为 axios 的浏览器兼容性。
![image](https://user-images.githubusercontent.com/14801448/43245443-e4f56258-90e0-11e8-8179-6be5fe8923a1.png)

360浏览器 、2345都有IE内核的模式，注意一下版本。

**Comment by snowkeda** [comment]
是否兼容ie8

**Comment by justquanyin** [comment]
麻烦具体描述下问题。 你是说antd-admin的示例内axios.js的兼容性问题么？还是问北斗框架的兼容性？

**Comment by snowkeda** [comment]
北斗框架在ie8下的兼容性， 我看到build 后有生成manifest.js 。 在ie8下有报错。

**Comment by njugray** [comment]
北斗提供的react应用同构开发的能力，浏览器兼容性更多地属于前端开发的范畴，使用不同的前端库会有不同的兼容性场景，比如React16已经是不支持IE8的了，如果需要满足兼容性需求，则必须引入不同的polyfill，比如最常见的 babel-polyfill 及 [es5-shim](https://github.com/es-shims/es5-shim)，在某些情况下无法完美兼容时，就需要开发者在不同的技术体系中做出取舍。

这些兼容性解决方案不会包括在 北斗的示例 里，应为这不是框架关注的重点，如果有兼容性需求无法满足，可以在这里寻求帮助，我们会尽力解答。

**Comment by njugray** [comment]
无新回复，先关闭了
