### ISSUE TITLE
安装报错，如图 c++没有安装

### ISSUE THREAD

**Issue by wunayou** [alibaba/beidou#7]
![image](https://user-images.githubusercontent.com/25662123/34241330-bbbe60ec-e64f-11e7-824d-395607695154.png)

是不是我布到服务器的时候 也会有这种问题  还是我这个电脑的问题

**Comment by wunayou** [comment]
环境 node 8.9  windows 7 （只是windows7特别存在的问题吗？）

**Comment by weichunpeng** [comment]
@wunayou 是通过 beidou-init 初始化出来的模板依赖安装不成功吗？ 请提供下完整的复现方式，谢谢
另外，可以用cnpm来安装node-sass, 参考下如下方式

https://github.com/lmk123/blog/issues/28

https://cnodejs.org/topic/5637549fd426a1404cbd0614

**Comment by njugray** [comment]
@wunayou 
node-sass 安装失败,  机器编译环境存在问题.
解决方法参考: 
https://stackoverflow.com/questions/21658832/npm-install-error-msb3428-could-not-load-the-visual-c-component-vcbuild-ex/39235952#39235952
