### ISSUE TITLE
Warning: Text content did not match. Server Client

### ISSUE THREAD

**Issue by zhou0818** [alibaba/beidou#71]
* **Node Version**: v8.11.3
* **Beidou Version**: 1.0.7
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:  16.2.0
* **Platform**: win10
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior

用 beidou-cli 的 simple 建的项目，跟着从零开始的教程在做，beidou dev 后，到编写 controller 这一步。访问  http://localhost:6001/news ，只要修改了 client/news.jsx 的内容，控制台就会报：

 Warning: Text content did not match. Server: "News" Client: "News123" 这种错误，必须重新beidou dev 一下

## Expected behavior

希望不要重新编译

**Comment by justquanyin** [comment]
能把client/neww.jsx和controller中的method主要代码逻辑贴一下么？

**Comment by zhou0818** [comment]
client/news.jsx 代码如下：
`import React from 'react'

export default class News extends React.Component {
  render() {
    return (
      <div>
        <h1>News</h1>
        <p>This is a news app</p>
        <button onClick={() => alert('it works~')}>Click Me</button>
      </div>
    )
  }
}`

controller/news.js 代码如下:
`
const Controller = require('beidou-core').Controller

class NewsController extends Controller {
  async show() {
    const news = await this.ctx.service.news.get()
    await this.ctx.render('index', {
      news
    })
  }
}

module.exports = NewsController`

**Comment by justquanyin** [comment]
我这面按照你贴出来的代码试了一下，没有出现报错。 不知道是不是你代码这面贴的不全。

**Comment by njugray** [comment]
无法复现，先关闭
