### ISSUE TITLE
antd加载问题

### ISSUE THREAD

**Issue by alex-my** [alibaba/beidou#72]
在使用`antd`的时候会有这样的提醒

> You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

我安装了`babel-plugin-import`
在`config.default.js`增加了配置

```text
'use strict';

const path = require('path');

module.exports = {
  keys: 'key',
  webpack: {
    custom: {
      configPath: path.join(__dirname, './webpack.config.js'),
    },
  },
  router: {
    root: '/pages',
    entry: 'page',
  },
  react: {
    static: true,
  },
 // ------------ 加了以下内容 ------------
  isomorphic: {
    babel: {
      plugins: [
        [
          require.resolve('babel-plugin-import'),
          { libraryName: 'antd', libraryDirectory: 'es', style: 'css' },
        ],
      ],
    },
  },
};

```
不过运行后报错:

```text
2018-08-09 18:16:09,304 ERROR 33391 [-/127.0.0.1/-/55ms GET /] nodejs.SyntaxError: Unexpected identifier
(function (exports, require, module, __filename, __dirname) { import Button from './button';
                                                                     ^^^^^^

SyntaxError: Unexpected identifier
    at new Script (vm.js:74:7)
    at createScript (vm.js:246:10)
    at Object.runInThisContext (vm.js:298:10)
    at Module._compile (internal/modules/cjs/loader.js:657:28)
    at Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Object.require.extensions.(anonymous function) [as .js] (/Users/zhangzuhong/Code/MyWork/beidou-boilerplate/node_modules/babel-register/lib/node.js:152:7)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
```
是不是`babel-plugin-import`配置的方法不对，我尝试了其它方式也没成功。

基于 `advanced` 版本。

**Comment by justquanyin** [comment]
引用了 babel-plugin-import ， 以及使用了antd 的 Button组件， 未复现出问题，如方便，能贴出可复现的代码么？ 或者加入钉钉群讨论一下

**Comment by alex-my** [comment]
引用`babel-plugin-import`，需要什么配置嘛。
这里就是一个引入了antd的`advanced `工程，然后看到警告，就添加了`babel-plugin-import`，但不知道如何在`beidou`中配置这个插件。

**Comment by alex-my** [comment]
我写的代码在这里: [https://github.com/alex-my/beidou-boilerplate](https://github.com/alex-my/beidou-boilerplate)
`config/config.default.js` 第25到28行是我的配置，但应该是没有配置正确，目前被我注释了。

**Comment by njugray** [comment]
@alex-my `babel-plugin-import` 是用来按需加载 antd 组件的 babel 插件，这部分功能主要用来减少js bundle的体积，对于node端意义不大。

```js
isomorphic: {
    babel: {
      plugins: [
        [
          require.resolve('babel-plugin-import'),
          { libraryName: 'antd', libraryDirectory: 'es', style: 'css' },
        ],
      ],
    },
  },
```
这部分配置是对服务端生效的，你的目的应该想是在webpack打包中启用

如果想要启用 `babel-plugin-import`，可以这么写：

1.  修改 config/config.default.js, 启用自定义webpack配置
```js
webpack: {
    custom: {
      configPath: path.join(__dirname, './webpack.config.js'),
    },
  },
```

2. 在 config/webpack.config.js 中修改babel-loader 配置，启用 .babelrc

```js
module.exports = (app, defaultConfig /* , dev */) => {
  const babelLoader = defaultConfig.module.rules[0];

  babelLoader.use.options.babelrc = true;

  return defaultConfig;
};

```

> defaultConfig的内容可以在 run/webpack.local.json 里查看 dump，babel-loader 是默认配置中的第一个 module.rule

3. 在 .babelrc 中添加需要的配置

```json
{
  "plugins": [["import", {
    "libraryName": "antd",
    "style": true
  }]]
}
```

**Comment by DXD23-SJTU** [comment]
兄弟，你热加载可以用吗

**Comment by alex-my** [comment]
目前需要手动刷新下页面，还没细看，今天周末我好好看看。

**Comment by DXD23-SJTU** [comment]
嗯嗯，我昨晚试了下可能是通用bug.我提个issue

**Comment by njugray** [comment]
@DXD23-SJTU simple示例
![2018-08-11 11 09 44](https://user-images.githubusercontent.com/5938871/43987685-66b35a48-9d57-11e8-97f7-f704b055a6aa.gif)

**Comment by alex-my** [comment]
@njugray 用以上方法尝试了下, 仍然会有警告
> You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.

`.babelrc`文件也生效了。代码见[https://github.com/alex-my/beidou-boilerplate](https://github.com/alex-my/beidou-boilerplate)

**Comment by njugray** [comment]
@alex-my 上述方法是antd按需加载的配置方式，至于你这个告警我无法复现，如果实在node端上打印的话，没有影响的，node上引打包还是小包没大区别

**Comment by DXD23-SJTU** [comment]
我也发现没用，也没报错。。。打出来的index.js永远是2.2M无论我的组件是多还是少

**Comment by njugray** [comment]
@DXD23-SJTU 
配置前：
![image](https://user-images.githubusercontent.com/5938871/44009656-eb27e558-9edf-11e8-8fc2-ae1bad1dc2cd.png)
配置后：
![image](https://user-images.githubusercontent.com/5938871/44009674-054c221e-9ee0-11e8-8cb6-eb2c5e3f747b.png)

**Comment by yangbo5207** [comment]
配置了babel import 同样没有生效，前后打包大小没变化 ~

**Comment by justquanyin** [comment]
你用的哪个例子？ 或者把wepack的配置贴一下？

**Comment by Oligocalse** [comment]
> @alex-my `babel-plugin-import` 是用来按需加载 antd 组件的 babel 插件，这部分功能主要用来减少js bundle的体积，对于node端意义不大。
> 
> ```js
> isomorphic: {
>     babel: {
>       plugins: [
>         [
>           require.resolve('babel-plugin-import'),
>           { libraryName: 'antd', libraryDirectory: 'es', style: 'css' },
>         ],
>       ],
>     },
>   },
> ```
> 
> 这部分配置是对服务端生效的，你的目的应该想是在webpack打包中启用
> 
> 如果想要启用 `babel-plugin-import`，可以这么写：
> 
> 1. 修改 config/config.default.js, 启用自定义webpack配置
> 
> ```js
> webpack: {
>     custom: {
>       configPath: path.join(__dirname, './webpack.config.js'),
>     },
>   },
> ```
> 
> 1. 在 config/webpack.config.js 中修改babel-loader 配置，启用 .babelrc
> 
> ```js
> module.exports = (app, defaultConfig /* , dev */) => {
>   const babelLoader = defaultConfig.module.rules[0];
> 
>   babelLoader.use.options.babelrc = true;
> 
>   return defaultConfig;
> };
> ```
> 
> > defaultConfig的内容可以在 run/webpack.local.json 里查看 dump，babel-loader 是默认配置中的第一个 module.rule
> 
> 1. 在 .babelrc 中添加需要的配置
> 
> ```json
> {
>   "plugins": [["import", {
>     "libraryName": "antd",
>     "style": true
>   }]]
> }
> ```

在启用之后再进行打包，虽然没有报错，但是也没有生效
![image](https://user-images.githubusercontent.com/36029402/57285846-aedcb680-70e6-11e9-969c-75464e565327.png)
![image](https://user-images.githubusercontent.com/36029402/57285883-bef49600-70e6-11e9-8cba-34d626e77e43.png)
![image](https://user-images.githubusercontent.com/36029402/57286060-1abf1f00-70e7-11e9-91e1-b11077bd9198.png)

**Comment by alex-my** [comment]
实际上antd按需加载是实现了的，可以用`webpack-bundle-analyzer`这个插件看看。

<img width="1328" alt="antd" src="https://user-images.githubusercontent.com/3118939/57347897-9b812800-7186-11e9-9d7c-c2db1c79918b.png">

实际上，无论是用`babel-plugin-import`还是手动引入，都这么大。
而真正大的是左侧的红框圈起来的。
