### ISSUE TITLE
示例simple的onClick事件只在组件里面有效，其他地方全部无效

### ISSUE THREAD

**Issue by kelvinXueLei** [alibaba/beidou#79]

**Comment by DXD23-SJTU** [comment]
能具体点吗

**Comment by kelvinXueLei** [comment]
这里面的button点击没反应
//index.jsx
export default class View extends React.Component {
    render() {
        let { helper, news } = this.props;
        return (
            <html>
                <head>
                    <title>Styling</title>
                    <link rel="stylesheet" href={helper.asset('/index.css')} />
                </head>
                <body>
                    <div>
                        {news.map((item) => {
                            return <a href={item.href} key={item.title}> {item.title} </a>
                        })}
                        <button onClick={() => alert('it works!')}>click me</button>
                    </div>
                    <script src={helper.asset('/manifest.js')} />
                    <script src={helper.asset('/index.js')} />
                </body>
            </html>
        );
    }
}

组件里面的点击事件就可以
//app.jsx
const App = () => (
  <div>
    <h1 className="title">Script</h1>
    <p>
      Scripting page template in `/client/script/index.jsx`, visit via url
      `/script`
    </p>
    <p>CSS file serves at `/build/script.css`</p>
    <p>JS file serves at `/build/script.js`</p>
    <hr />
    <button onClick={() => alert('it works!')}>click me</button>
  </div>
);

export default hot(module)(App);

//index.jsx
export default class View extends React.Component {
  static getPartial() {
    return {
      html: <App />,
    };
  }

  render() {
    const { helper, html } = this.props;
    return (
      <html>
        <head>
          <title>Script</title>
          <link rel="stylesheet" href={helper.asset('/script.css')} />
        </head>
        <body>
          <div id="container" dangerouslySetInnerHTML={{ __html: html }} />
          <button onClick={() => alert('it works!')}>click</button>
          <script src={helper.asset('/manifest.js')} />
          <script src={helper.asset('/script.js')} />
        </body>
      </html>
    );
  }
}

if (__CLIENT__) {
  ReactDOM.hydrate(<App />, document.getElementById('container'));
}

**Comment by DXD23-SJTU** [comment]
需要点击事件的地方调用下ReactDom.hydrate注水一下，详细用法可以参阅react文档

**Comment by njugray** [comment]
@kelvinXueLei index.jsx 里的 `View` 在服务端渲染，app.jsx 里的部分（通过 `getPartial()` 指定），通过 `ReactDOM.hydrate()`会同时在客户端和服务端渲染

只有在客户端里渲染的内容会绑定事件，服务端输出的只是纯 HTML
