### ISSUE TITLE
不能热更新

### ISSUE THREAD

**Issue by wunayou** [alibaba/beidou#8]
步骤 
npm install beidou-init -g
beidou init  选择 简单的
npm run start

然后修改 一点 点东西 

webpack显示更新完成 

但是i浏览器的东西不变

**Comment by wunayou** [comment]
![image](https://user-images.githubusercontent.com/25662123/34286845-59d7bdae-e71e-11e7-91be-c2c1634a00f5.png)

**Comment by wunayou** [comment]
![image2](https://user-images.githubusercontent.com/25662123/34286879-89c79278-e71e-11e7-9950-298148868516.png)

**Comment by njugray** [comment]
@wunayou 
你图中修改的部分代码是 **纯服务端(server-side)** 运行的代码,  无法进行热更新

热更新必须在 **客户端(client-side)** 代码中生效.

目前还没有专门针对 HMR的示例, 后续会添加.

`redux` 中, HMR是生效的, 可以先参考下

**Comment by wunayou** [comment]
thank you 解决了  继续发现其它的坑

**Comment by wunayou** [comment]
redux 与router为什么没有结合起来

**Comment by njugray** [comment]
结合 Router 的使用方法可以查看  [tree/develop/examples/antd-admin](https://github.com/alibaba/beidou/tree/develop/examples/antd-admin) 示例, 包含两个服务端路由和多个浏览器端路由

**Comment by wunayou** [comment]
@njugray   谢谢你的回答  我看一下代码心中有一个问题   现在大部分的同构是不是都是一个页面一个react 页面  

因为看到 login与 dashboard分开的react单页

**Comment by njugray** [comment]
login和dashboard是两个页面, 同时dashboard是一个SPA.

> 现在大部分的同构是不是都是一个页面一个react 页面

每个页面都会有一个 `React View`, 在这个例子中是两个. 作用相当于传统视图层(jade, jstl, xtemplate), 只是以React方式实现, 保持编码习惯的一致

**Comment by KingsleyYu** [comment]
项目：beidou/examples/simple 

步骤：
1. npm init 
2. npm start

浏览器地址栏输入：http://127.0.0.1:6001/style  

问题：
1. 未能成功加载到style.css 
![image](https://user-images.githubusercontent.com/5172951/38131008-da5b48cc-3437-11e8-8305-fd1d6698ac7f.png)
2. 未能热更新。看见上面回复是说修改的部分代码是 纯服务端(server-side) 运行的代码, 无法进行热更新
    热更新必须在 客户端(client-side) 代码中生效. 
    问题是simple 中的代码哪些算是client-side 的代码？通过__CLIENT__  判断运行的代码是客户端代码？

@njugray  盼回

**Comment by njugray** [comment]
@KingsleyYu 
抱歉回复晚了

本地开发用 `npm run dev` 启动,  npm start 是生产环境模式运行, 本地的webpack插件不会启动的

**Comment by wind13** [comment]
我也遇到不能热更新的问题：

- 已经使用 `npm run dev` 启动；
- 修改的也是 `client` 目录下的 `index.jsx` 文件；
