### ISSUE TITLE
关于前端配置定制的问题

### ISSUE THREAD

**Issue by DXD23-SJTU** [alibaba/beidou#80]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
现在的话 node环境下根据不同的开发环境或者生产环境去自定义配置是没有问题的。如何在浏览器端也可以自定义配置？发现ctx的数据内容首屏渲染的时候如果不在script标签注册一下ReactDom.hydrate后是无法读取这些信息的

## Expected behavior
有什么好的方法可以让浏览器端也能根据不同环境去自定义配置文件呢?

**Comment by justquanyin** [comment]
可以尝试一下服务端接口输出客户端想用的配置文件
(服务端根据node环境判断输出对应的配置文件)

不知道是否是你需要的

**Comment by DXD23-SJTU** [comment]
嗯嗯
