### ISSUE TITLE
如何分路去获取打包js,css静态资源文件？(按需加载)

### ISSUE THREAD

**Issue by DXD23-SJTU** [alibaba/beidou#81]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
现在是将一个页面上的所有组件都打包成一个js，势必会加载很大的脚本文件，思考：如何实现按需加载

## Expected behavior
比如我再点击一个前端路由后，这是浏览器会get一下这部分的静态资源再进行渲染

**Comment by DXD23-SJTU** [comment]
react-router-4的[Code Splitting](https://reacttraining.com/react-router/web/guides/code-splitting)我是不是可以借鉴一下并用到beidou中去呢?

**Comment by DXD23-SJTU** [comment]
我按照react-router-4的Code Splitting做了一遍，发现并没有按需加载，期待大佬给出新的方案

**Comment by njugray** [comment]
看下这个示例 https://github.com/alibaba/beidou/tree/examples/with-react-loadable/examples/with-react-loadable

#46

**Comment by DXD23-SJTU** [comment]
嗯，实现了一下很好玩，接下去有个问题怎么让这些静态资源匹配到cdn上去，我打算调整webpack打包时候的路径

**Comment by DXD23-SJTU** [comment]
发现一个例子里面疏漏的地方，如果加载了antd，并且启用了.babelrc文件的话，同样需要在.babelrc文件中加入配置代码，以下是我的配置文件，查了我4个小时。。。。
```javascript
{
    "plugins": [
        "dynamic-import-node",
        [
            "import-inspector",
            {
                "serverSideRequirePath": true
            }
        ],
        [
            "import",
            {
                "libraryName": "antd",
                "style": true
            }
        ]
    ]
}
```

**Comment by DXD23-SJTU** [comment]
今天测试打包的时候发现antd的.babelrc配置还是会和React-loadable的isomorphic配置有冲突，当我采用上一层楼的配置方法之后，直接就没有了按需加载的功能，拿到的js都是整个的。

**Comment by DXD23-SJTU** [comment]
经过一天多的排查，发现了问题所在：webpack自定义配置的entry.
之前在webpack.config.js自定义entry配置的时候都是直接
```javascript
    defaultConfig.entry["admin_login"] = [
        "/Users/xudading/工作/www/lark/client/pages/admin/login.jsx"
    ];
```javascript
后来改变了写法，改成：
```
defaultConfig.entry = {
            ...defaultConfig.entry,
            "admin_login": [
                "/Users/xudading/工作/www/lark/client/pages/admin/login.jsx"
            ]
}
```
这样便解决了问题和antd的.babelrc无关。更正一下。以后如果还有问题，再打开这个issue

**Comment by DXD23-SJTU** [comment]
至于之前那种更改entry配置的方法为什么不行，还想请教 @njugray
