### ISSUE TITLE
跑测试环境的时候，env设置为test，为什么会加载不到build文件夹里面的资源。

### ISSUE THREAD

**Issue by kelvinXueLei** [alibaba/beidou#82]
//package.json 里面的启动命令
 "start": "beidou start --port=6051 --env=prod --daemon --workers=1 --title=web-react-srr",
   "test":"beidou start --port=6051 --env=test --daemon --workers=1 --title=web-react-srr",

//config.test.js
module.exports = {
  keys: 'secrets',
  react: {},
  test:1
};

//config.prod.js
module.exports = {
    keys: 'secrets',
    react: {},
    url: 'http://47.97.123.158:8880',
    test:2111
};

我跑npm run test的时候，页面就加载不到js和css，但是跑npm start的时候就可以加载得到。这是什么原因

**Comment by njugray** [comment]
`--env=test` 属于自定义 env了，内置的测试环境是 `unittest`，改环境下启用的插件和配置由对应的plugin.{env}.js 和 config.{env}.js 定义，如 config.unittest.js，分别从项目到底层框架，前者复写后者 ( project -> beidou -> eggjs)

因为 `env=test` 下部分来自框架的配置确实，需要自己修改 config.test.js ，如你这个case里的，应该是 static 的配置在 test 环境下 和 prod 环境不一致，prod下的配置文件看这里：https://github.com/alibaba/beidou/blob/master/packages/beidou-core/config/config.prod.js

```js
static: {
    prefix: '/build',
    dir: path.join(appInfo.baseDir, 'build/'),
    dynamic: false,
    preload: true,
  },
```

**Comment by kelvinXueLei** [comment]
好的，应该是我的env是自定义的，所以可能有环境参数有什么不一样的。现在把prod里的静态目录指到build里面就可以了。感谢
