### ISSUE TITLE
希望有的功能：打包编译的时候可以指定环境

### ISSUE THREAD

**Issue by DXD23-SJTU** [alibaba/beidou#83]
* **Node Version**:
* **Beidou Version**:
* **Plugin Name And Version**:
* **React/ReactDOM Versions**:
* **Platform**:
* **Mini Showcase Repository**:
* **Other Info**:

## Current behavior
现在在运行 npm run build 的时候，发现env只是简单的prod，并不能利用到egg的自定义env

## Expected behavior
如果在npm run build的时候传入环境参数，然后能获取到app.config.env这样的自定义环境参数就很棒了，这样的化我就能根据不同的环境去打包匹配静态资源的路径等等操作

**Comment by njugray** [comment]
执行 `beidou build` 的时候可以传入 `--dev` 参数，在自定义配置中, 变量 `dev` 为 `true`，可以根据此变量选择性地读取配置和配置webpack插件  

```js
// webpack.config.js

module.exports = (app, defaultConfig, dev, target) => {
  if (dev) {
    // do something
  }
};
```

`app.config.env` 这种变量是可以取到的，但构建的时候，环境恒为 `local`，因为其他环境下，webpack插件不会启用，框架也就不会加载它的默认配置，构建过程无法进行。

--dev 用来区分 两套配置 （开发和生产）是够用的

**Comment by DXD23-SJTU** [comment]
嗯，我现在用的就是两套，我再琢磨琢磨。谢谢。
