### ISSUE TITLE
webpack.config.js 出错

### ISSUE THREAD

**Issue by 18613109040** [alibaba/beidou#86]
const path = require('path');
const {
  imageLoaderConfig,
  fileLoaderConfig,
  getStyleCongfigs
} = require('beidou-webpack/config/webpack/utils')

module.exports = (app, defaultConfig, dev ) => ({
  ...defaultConfig,
  module: {
    ...defaultConfig.module,
    rules: [
      {
        test: /\.(js|jsx|mjs)$/,
        exclude: /node_modules/,
        use: {
          loader: require.resolve('babel-loader'),
          options: {
            babelrc: false,
            presets: [ require.resolve('babel-preset-beidou-client') ],
            plugins: [
              'react-hot-loader/babel',
              'transform-decorators-legacy',
              ['transform-runtime', {
                polyfill: false,
              }], 
              ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true}]
            ],
            // This is a feature of `babel-loader` for webpack (not Babel itself).
            // It enables caching results in ./node_modules/.cache/babel-loader/
            // directory for faster rebuilds.
            cacheDirectory: dev,
            compact: !dev,
            highlightCode: true,
          },
        },
      },
      ...getStyleCongfigs(dev),
      imageLoaderConfig,
      fileLoaderConfig,
    ],

  },

控制台报 错
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In \node_modules\_babel-preset-beidou-client@1.0.8@babel-preset-beidou-client\index.js

**Comment by njugray** [comment]
你这是用了 bable@7 吧
> All plugins/presets should now export a function rather than an object for consistency [via babel/babel#6494]. This will help us with caching.

babel@7目前处在 RC.1 版本，正式发布后会对beidou内置的babel做一次升级

你遇到的这个问题，可以先不引入 babel-preset-beidou-client，自行引入需要的 preset 即可

**Comment by 18613109040** [comment]
谢谢

**Comment by 18613109040** [comment]
const path = require('path');
const {
  imageLoaderConfig,
  fileLoaderConfig,
  getStyleCongfigs
} = require('beidou-webpack/config/webpack/utils')

module.exports = (app, defaultConfig, dev ) => ({
  ...defaultConfig,
  module: {
    ...defaultConfig.module,
    rules: [
      {
        test: /\.(js|jsx|mjs)$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: {
            babelrc: false,
            presets: [
              "es2015", 
              "react",  
              "stage2",
              ["env", {
                "modules": false
              }]
            ],
            plugins: [
              "transform-decorators-legacy",
              "transform-class-properties",
              ['transform-runtime', {
                polyfill: false,
              }], 
              ["import", { "libraryName": "antd", "libraryDirectory": "es", "style": true}]
            ],
            env: {
              development: {
                plugins: [
                  "react-hot-loader/babel"
                ]
              }
            },
            cacheDirectory: dev,
            compact: !dev,
            highlightCode: true,
          },
        },
      },
      ...getStyleCongfigs(dev),
      imageLoaderConfig,
      fileLoaderConfig,
    ],

  },
  resolve: {
    extensions: ['.json', '.js', '.jsx'],
    alias: {
      components: path.join(__dirname, '../client/components'),
    },
  },
});

你好我改成这样还是
Module build failed: Error: Plugin/Preset files are not allowed to export objects, only functions. In G:\igola\igola-cms\node_modules\babel-preset-es2015\lib\index.js
    at createDescriptor (G:\igola\igola-cms\node_modules\_@babel_core@7.0.0-beta.46@@babel\core\lib\config\config-descriptors.js:181:11)
    at G:\igola\igola-cms\node_modules\_@babel_core@7.0.0-beta.46@@babel\core\lib\config\config-descriptors.js:106:12    at Array.map (<anonymous>)

**Comment by njugray** [comment]
确认下安装的 preset 和 plugin 版本，babel@7启用了独立的 namespace: @babel , 参考babel的文档安装对应的包。

比如 @babel/preset-es2015

**Comment by 18613109040** [comment]
谢谢
