### ISSUE TITLE
新手问题（初视数据加载问题）

### ISSUE THREAD

**Issue by wunayou** [alibaba/beidou#9]
redux的demo

刚进来的时候
```
在入口文件 page.jsx
有一个初始值 
 const store = configureStore({
      greeting: 'beidou',
    });
```

```
页面加载完以后还是一个请求
在/contains/index.jsx里面
componentDidMount() {
    this.props.dispatch(actions.greet());
  }
```
然后造成的结果是

传过来是源代码
<div class="page">
  | <h1>Redux Example</h1>
  | <p>Hello, beidou</p>
  | </div>

然后JS的请求
改变了“beidou” 变成"everyone"(yield put(actions.success('everyone')); )

这个现象是正常吗？

如果我想要 设了初始值 就不请求 可以吗？（有人是这样弄的吗？）

**Comment by njugray** [comment]
如果在 store中, 需要的数据已经准备就绪, 可以不需要在客户端发送请求.

不需要在服务端渲染的内容, 可以通过这种方式:  在 `didMount` 中去请求需要的数据.
