### ISSUE TITLE
自定义webpack less规则会出错

### ISSUE THREAD

**Issue by chenmingjia** [alibaba/beidou#93]
我想请教一下，我按step-by-step.md里做，但只是把styl换成less，就不行了，调了半天也没通

本意想给less加个postcss，但是试过自定义css，less的规则都会报这种错误，是不是默认支持的如css，less，sass不能这样直接改

webpack.js

```
const ExtractTextPlugin = require('extract-text-webpack-plugin');

module.exports = (app, defaultConfig, dev) => {
  // 添加 .less 文件支持
  defaultConfig.module.rules.push({
    test: /\.less$/,
    loader: ExtractTextPlugin.extract({
      fallback: require.resolve('style-loader'),
      use: [
        require.resolve('css-loader'), 
        require.resolve('less-loader'),
        require.resolve('postcss-loader')
      ],
    })
  });
  defaultConfig.plugins.push(
    new ExtractTextPlugin('[name].css')
  );
  return defaultConfig;
};
```

报错如下：

ERROR in ./node_modules/_css-loader@0.28.11@css-loader??ref--5-2!./node_modules/_postcss-loader@2.1.6@postcss-loader/lib??postcss!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js??ref--5-4!./node_modules/_extract-text-webpack-plugin@3.0.2@extract-text-webpack-plugin/dist/loader.js??ref--9-0!./node_modules/_style-loader@0.19.1@style-loader!./node_modules/_css-loader@0.28.11@css-loader!./node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js!./node_modules/_postcss-loader@2.1.6@postcss-loader/lib!./client/detail.less
Module build failed:

// load the styles
var content = require("!!../node_modules/_css-loader@0.28.11@css-loader/index.js!../node_modules/_less-loader@4.1.0@less-loader/dist/cjs.js!../node_modules/_postcss-loader@2.1.6@postcss-loader/lib/index.js!./detail.less");
          ^
Unrecognised input
      in D:\CMJ Test Project\Beidou-New\client\detail.less (line 4, column 12)
 @ ./client/detail.less 4:14-594 18:2-22:4 19:20-600
 @ ./client/headline.jsx
 @ ./client/news.jsx
 @ ./client/index.jsx
 @ multi ./node_modules/_webpack-dev-server@2.11.3@webpack-dev-server/client?http://0.0.0.0:6002 (webpack)/hot/only-dev-server.js ./client/index.jsx

**Comment by ForeverPx** [comment]
我也遇到了同样的问题

**Comment by njugray** [comment]
@ForeverPx 提供复现场景，然后新开一个issue
