### ISSUE TITLE
beidou部署到阿里云报500错误

### ISSUE THREAD

**Issue by chenmingjia** [alibaba/beidou#98]
按照官方文档
https://github.com/alibaba/beidou/blob/master/packages/beidou-docs/zh/deployment/deployment.md
的部署流程
{
  "scripts": {
    "start": "egg-scripts start --daemon",
    "stop": "egg-scripts stop"
  }
}
这样配置本地和线上 npm start 可以运行，但访问直接是500内部错误。

将scripts 改成
 "start": "beidou start",
"debug": "beidou debug",
 "stop": "beidou stop",

发布到线上才不会出错，想问一下，beidou start 和 egg-scripts start --daemon 的区别。

在阿里云的Node.js 性能平台也找不到500的错误原因，想请教一下

**Comment by njugray** [comment]
@chenmingjia 使用 egg-script 启动时，需要通过 --framework=beidou-core 指定框架为beidou

beidou start 等同于 egg-bin start
